### ISSUE TITLE
Approbation setup

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-browser#104]
## Tasks

- [x] Create spec doc
- [x] Work out how to hook up the new spec to the test runs and reports
- [x] Set up / make work the CI reporting
- [x] Make repo public
- [ ] Check it works
