### ISSUE TITLE
Enable deploy previews

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-browser#106]
Could we set up a netlify against a mocked backend? 

## Tasks

Emil has something working right now, we need to:

- [ ] Verify whether this gives us what we need to be able to preview work in progress without having to make a release
- [ ] If it does - do nothing more, great job!
- [ ] If it doesn't, do what we need to do to make it possible (OR create tickets for the work needed to do it if it's too big for this sprint)
