### ISSUE TITLE
Log in (next time password expires)

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#114]
## Story 

As a wallet user 
I want a way to enter my password when my login has expired 
So that I can continue with my task

## Acceptance Criteria 

- [x] When I have quit my browser, and then reopened, I am asked to enter my browser extension password
- [x] I am informed if I enter my password incorrectly 
- [x] When entering a correct password decrypts my wallets

## Tasks

- [X] Detailed sketch
- [X] Visual design
- [X] Implement UI
- [x] Integrate with backend
- [x] Write unit tests
- [x] Write end to end tests
- [x] Code review
- [x] Team verify acceptance criteria met
- [x] Exploratory QA testing 
- [x] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [x] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [x] Add story and A/Cs to spec doc 
- [x] Review with stakeholders
- [x] Release

**Comment by ckpringle** [comment]
Needs a log in API @emilbayes
