### ISSUE TITLE
Coming back to the app after onboarding

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#116]
## Story

As a user
I want to see my wallet / keys immediately when I open my extension (and not onboarding again) 
So that I don't need to repeat onboarding unnecessarily and continue my task easily...

## Acceptance Criteria 

- [x] There is a way to determine if user has onboarded 
- [x] I want to see the previous page I was on or my wallet page by default

## Tasks

- [X] Detailed sketch
- [x] Visual design
- [X] Implement UI
- [X] Integrate with backend
- [X] Write unit tests
- [x] Write end to end tests
- [X] Code review
- [x] Team verify acceptance criteria met
- [x] Team verify acceptance criteria met
- [x] Exploratory QA testing 
- [x] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [x] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [x] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release
