### ISSUE TITLE
Get started

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#117]
## Story

As a browser wallet user
When I am using the browser wallet for the first time
I want to be oriented as to what the app is/does and clear on my options/next steps
So that I feel reassured and know what to do next

## Acceptance Criteria

- [x] There is a way to understand at a glance what Vega wallet does / be assured it's safe / secure (but not too safe / secure, it's alpha software still!!)
- [x] There is a way to get to the next step
- [x] If I already have a wallet and passphrase I don't see this screen, I see my wallet / keys

## Tasks

- [X] Detailed sketch including definition of the Vega Wallet "proposition" i.e. key points / features / usages
- [X] Visual design
- [x] Implement UI & Integrate with backend
- [x] Write unit tests
- [x] Write end to end tests
- [x] Code review
- [x] Team verify acceptance criteria met
- [x] Team verify acceptance criteria met
- [x] Exploratory QA testing 
- [x] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [x] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [x] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release
