### ISSUE TITLE
Create app password

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#118]
## User Story

As a browser wallet user
I want to create a password for my browser wallet app
So that I can secure my wallets and keys on this device

## Acceptance Criteria

- [x] When I haven't submitted my password, I can go back to the previous step
- [x] I can see an explanation of what the password is for and that it cannot be used to recover my keys or recover itself
- [x] I can enter a password for the browser wallet
- [x] I can verify the password I set for my browser wallet (to help ensure I typed it correctly and can replicate it)
- [x] I can verify that I understand that Vega doesn't store and therefore can't recover this password if I lose it
- [x] I can NOT submit an empty password
- [x] I can submit the password I entered
- [ ] When I have submitted my new password, I am given some feedback that it was set successful
- [x] When I have submitted my new password, I am taken to the next step
- [x] When I have submitted my new password, I can NOT go back to the previous step
- [x] After setting a password, my wallets are encrypted

## Tasks

- [X] Detailed sketch
- [X] Visual design
- [x] Implement UI
- [x] Integrate with backend
- [x] Implement Authentication (encryption)
- [x] Write unit tests
- [x] Write end to end tests
- [x] Code review
- [x] Team verify acceptance criteria met
- [x] Exploratory QA testing 
- [x] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [x] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [x] Add story and A/Cs to spec doc 
- [x] Review with stakeholders 
- [x] Release
