### ISSUE TITLE
Create or import wallet

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#119]
## Story 

As a browser wallet user
I want to decide whether to create a new wallet or import an existing one
So that I understand my options and don't waste time creating a new wallet when I already created one elsewhere

## Acceptance Criteria

- [ ] I can choose to create a wallet
- [ ] I can choose to import an existing wallet

## Tasks

- [x] Detailed sketch
- [X] Visual design
- [X] Implement UI 
- [x] Integrate with backend
- [x] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [x] Review with stakeholders
- [ ] Release
