### ISSUE TITLE
Create new wallet (and key pair)

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#120]
## Story

As a browser wallet user
When I am using the browser wallet for the first time
I want to create a new wallet (and key pair)
So that I can get started using Console / another Vega dapp to trade / take part in governance

## Acceptance Criteria

- [x] I am provided with a recovery phrase for my new wallet that is initially hidden from view
- [x] I can see an explanation of what the recovery phrase is for and that it cannot be recovered itself
- [x] I can choose when to reveal/show the recovery phrase
- [x] I can copy the recovery phrase into my clipboard
- [x] I can verify that I understand that Vega doesn't store and therefore can't recover this recovery phrase if I lose it
- [x] The new Wallet name and key pair are auto generated in the background "Wallet 1" "Vega Key 1" 
- [x] When I have already created a wallet, I am redirected to the landing  page where I can view that wallet (rather than the onboarding flow)

## Tasks

- [X] Detailed sketch
- [X] Visual design
- [X] Implement UI
- [x] Integrate with backend
- [x] Write unit tests
- [x] Write end to end tests
- [x] Code review
- [x] Team verify acceptance criteria met
- [x] Exploratory QA testing 
- [x] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [x] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [x] Add story and A/Cs to spec doc 
- [x] Review with stakeholders
- [ ] Release

## Notes

Related tests written for desktop wallet that might be useful to refer to / reuse:
[0001-WALL-005](https://github.com/vegaprotocol/specs/blob/master/user-interface/0001-WALL-wallet.md#0001-WALL-005)
[0001-WALL-006](https://github.com/vegaprotocol/specs/blob/master/user-interface/0001-WALL-wallet.md#0001-WALL-006)
[0001-WALL-008](https://github.com/vegaprotocol/specs/blob/master/user-interface/0001-WALL-wallet.md#0001-WALL-008)
