### ISSUE TITLE
Import existing wallet

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#121]
## Story

As a wallet user
When I am using the browser extension for the first time
I want to import an existing vega wallet (and key pair(s)) that I created elsewhere i.e. desktop app or CLI
So that I can get started using Console / another Vega dapp to trade / take part in governance

## Acceptance Criteria

- [x] I can choose to import an existing vega wallet
- [x] I can see an explanation of what I am being asked to do 
- [x] I can enter the recovery  phrase to import my existing vega wallet
- [x] I can submit the recovery phrase I have entered to import the wallet
- [x] I can not hit submit until I have entered 24 words (and given feedback that I haven't met the min number of words)
- [x] If I submit a recovery phrase I am given feedback if the words are invalid i.e. no wallet found with that recovery phrase (and I can try again)
- [x] I am redirected to the next step

## Tasks

- [x] Detailed sketch
- [x] Visual design
- [x] Implement UI
- [x] Validation of right number of words and right words in recovery phrase
- [ ] Backend implementation
    - [x] Fetch and decode the config (brought over from previous ticket)
    - [x] Validate config (brought over from previous ticket)
    - [x] Save network config (brought over from previous ticket)
    - [ ] Implement algorithm
    - [ ] Validation
- [x] Integrate with backend
- [x] Write unit tests
- [x] Write end to end tests
- [x] Code review
- [x] Team verify acceptance criteria met
- [x] Exploratory QA testing 
- [x] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [x] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [x] Add story and A/Cs to spec doc 
- [x] Review with stakeholders 
- [ ] Release

## Design

Figma: https://www.figma.com/file/rFlT1Ip2ot7Zfr2E5Is3Pd/Browser-Wallet?type=design&node-id=3041-5767&t=qKO976OQwLgKKgN8-0

![Image](https://github.com/vegaprotocol/vegawallet-browser/assets/46783148/1b99feb1-53cc-4fe5-a67f-6648cddb62d9)

## Notes

Tests written against relevant desktop wallet A/Cs can be found here in case useful to refer to / reuse [0001-WALL-004](https://github.com/vegaprotocol/specs/blob/master/user-interface/0001-WALL-wallet.md#0001-WALL-004)
