### ISSUE TITLE
Spike: Investigate opt in to error reporting

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#122]
## Story

As a wallet user
When I am using the browser extension for the first time
I want to be able to decide whether to opt in to automatic error reporting or not
So that I remain in full control of my privacy

## Acceptance Criteria

- [ ] I can see an explanation of what I am being asked to opt in/out to and why
- [ ] I can click a link to read more details about Vega's privacy policy
- [ ] I can opt in to report bugs and crashes
- [ ] I can opt out of reporting bugs and crashes
- [ ] If I have opted in and am using the wallet app, telemetry errors / analytics are recorded / reported in Sentry
- [ ] If I have opted in and am using the wallet app, all keys are obscured and replaced with something appropriate in Sentry
- [ ] If I have opted out and am using the wallet app, telemetry errors / analytics are NOT recorded / reported in Sentry

## Tasks

- [ ] Create more detailed sketch and define content
- [ ] Review with stakeholders
- [ ] Visual Design
- [ ] Implement backend error reporting
- [ ] Implement Sentry error reporting
- [ ] QA Test
- [ ] Release

## Notes

Tests written against desktop wallet A/Cs can be found here, in case useful to reuse / refer to [0001-WALL-003](https://github.com/vegaprotocol/specs/blob/master/user-interface/0001-WALL-wallet.md#0001-WALL-003)

**Comment by ckpringle** [comment]
Need to investigate what Sentry allows and if that works first. If it's capturing errors from the backend process does that give us what we need / does it do that?

**Comment by dexturr** [comment]
Investigate which of these types of errors are captured by default by Sentry in the FE/BE:

- Background errors e.g. when the app is starting up 
    - These appear to be captured correctly
- Errors the backend throws in response to a request intended e.g. wallet with name X already exists
    -  Check
- Unexpected errors thrown in the backend
    - Check
- Errors from the frontend
    - Known to be covered by sentry
