### ISSUE TITLE
View wallet and key pair(s)

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#123]
## Story

As a browser wallet user
I want to view my vega wallet (and key pair(s))
So that I can see that I've been successful creating the wallet / see my key ID 

## Acceptance Criteria

- [ ] I can see a list of the keys in my wallet
- [ ] I can copy the public key ID to my clipboard
- [ ] I can see information of where to go to deposit and manage my assets
- [ ] I can see where I am in the app when viewing my wallet and key pair(s)

## Tasks

- [X] Detailed sketch
- [X] Visual design
- [X] Implement UI
- [x] Integrate with backend
- [x] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release

## Sketch
