### ISSUE TITLE
Remember where I am in the onboarding flow

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#124]
## Story 

As a browser wallet user
When I have started onboarding in the browser wallet and I close the extension / browser
I want to be able to reopen the extension and it remember where I was in the onboarding flow
So that I don't have to start again

## Acceptance Criteria

- [x] I can close the extension and when I reopen it it opens on the same page / view 
- [ ] When I reopen the extension after last viewing the recovery phrase and hadn't yet acknowledged and moved to the next step, I am reverted to choosing to create or import a wallet (this is a compromise to be addressed in #204 )

## Tasks

- [x] Implement UI
- [x] Integrate with backend
- [x] Write unit tests
- [x] Write end to end tests
- [x] Code review
- [x] Team verify acceptance criteria met
- [x] Exploratory QA testing 
- [x] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [x] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [x] Add story and A/Cs to spec doc 
- [x] Review with stakeholders
- [ ] Release
