### ISSUE TITLE
Default to fairground network

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#125]
## Story

As a wallet user
When I open the browser extension for the first time
I want to be automatically connected to a default network (initially fairground)
So that I can get straight to using the app

## Acceptance Criteria 

- [ ] Browser extension defaults to use Fairground network 
- [ ] There is a way to see in the UI the network I am connected to (currently covered in separate story https://miro.com/app/board/uXjVPUiQ2AE=/?openCardPanel=3458764551340889905)

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.
