### ISSUE TITLE
Smart data node

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#126]
## Chore 

We are currently selecting a node at random to connect to. On testnet we often have a lot of unhealthy nodes so we need to do something clever to find a healthy node to connect to when sending a transaction.

## Tasks

- [ ] Understand how this is done in the desktop wallet
- [ ]  Replicate this logic for browser wallet
- [ ]  Ensure we deal with edge cases i.e. what if there are no healthy nodes

## Additional details / background info

The console team are doing something similar but a bit more advanced that we may be able to leverage [vegaprotocol/frontend-monorepo#1899](https://github.com/vegaprotocol/frontend-monorepo/issues/1899)

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.
