### ISSUE TITLE
View network connected to

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#127]
## Story

As a browser wallet user
I want to know which vega network my browser wallet is connected to
So that I know if I am on the network I expect to be, and whether I am transacting with real or fake assets

## Acceptance Criteria

- [ ] The browser wallet defaults to use the Fairground network 
- [ ] I can see which vega network the browser wallet is connected to from everywhere in the app

## Tasks

- [x] Detailed sketch
- [x] Visual design
- [x] Implement UI
- [x] Integrate with backend
- [x] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release
