### ISSUE TITLE
View network details

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#128]
## Story

As a wallet user
I want to be able to see more details about the vega network my browser wallet is connected to
So that I know if I am on the network I expect to be, and understand more about it

## Acceptance Criteria

- [ ] There is a way to see the details (list of REST nodes) of the vega network the browser wallet is connected to

## Tasks

- [ ] Detailed sketch
- [ ] Visual design
- [ ] Implement UI
- [ ] Integrate with backend
- [ ] Backend
    - [x] Implement `admin.describe_network` (brought over from previous ticket)
    - [x] Should we save the original `.toml` file or present the configuration as the saved JSON? (brought over from previous ticket)
    - [ ] Expose the data in a way the UI can fetch it
- [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders 
- [ ] Release

## Additional details / background info

**Comment by JonRay15** [comment]
The multinetwork stuff covers this ... and some of the requirements about seeing nodes etc are covered by the apps and dont need to be in the wallet.
