### ISSUE TITLE
Notify of connection request in wallet

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#129]
## Story

As a wallet user
I want the app to notify me when I attempt to connect a dapp
So that I know what to do next 

## Acceptance Criteria 

- [ ] I see an indication on my extension icon to show that a dapp has initiated a connection to the wallet

## Tasks

- [x] Implement 
- [x] Write unit tests
- [ ] Write end to end tests
- [x] Code review
- [x] Team verify acceptance criteria met
- [x] Exploratory QA testing 
- [x] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [x] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [x] Add story and A/Cs to spec doc 
- [x] Review with stakeholders 
- [ ] Capture in Decision Log
- [ ] Release
