### ISSUE TITLE
Connect all key(s) only

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#130]
## Story
As a wallet user
I want to connect my key(s) to a dapp 
So that I can verify transactions like orders, transfers etc.

## Acceptance Criteria 

- [x] There is a way to approve or deny a connection request 
- [x] I can see what approving a connection request enables the site / dapp to do 
- [x] I can see a visual representation of the dapp requesting access e.g. the favicon 
- [x] I can see the URL of the site / dapp requesting access
- [x] All new connections are for all keys in a wallet and all future keys added to the wallet
- [x] There is a way to understand that i.e. this connection request gives access to ALL my keys now and in the future
- [x] When I go away from the extension and come back to the connected site, the browser extension remembers the connection and does not ask me to reconnect
- [x] If the had the browser wallet open when I instigated the connection request, the browser wallet returns your view to where you were before the request came in
- [x] When I try to connect to the wallet I've made during onboarding but have not "completed" onboarding, I cannot see the connection request until I've completed onboarding (it is queued in the background) 

## Notes
Connections are remembered in local session history

## Tasks

- [x] Finalise copy to meet ACs and update design
- [X] Detailed sketch
- [X] Visual design
- [x] Implement UI
- [x] Integrate with backend
- [x] Implement Authentication (encryption)
- [x] Write unit tests
- [x] Write end to end tests
- [x] Code review
- [x] Team verify acceptance criteria met
- [x] Exploratory QA testing 
- [x] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [x] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [x] Add story and A/Cs to spec doc 
- [x] Review with stakeholders 
- [x] Release

## Design 

![Image](https://user-images.githubusercontent.com/46783148/236441142-6bdcff7b-14b5-497f-87b4-14a9a496512b.png)

[Figma link ↳ ](https://www.figma.com/file/rFlT1Ip2ot7Zfr2E5Is3Pd/Browser-Wallet?node-id=3216%3A1730&t=nc14z0BJGNGq6bkv-1)
