### ISSUE TITLE
View connections

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#131]
## Story

As a wallet user
I want to see which dapps have permission to access my keys
So that I can understand who/what has access to my keys

## Acceptance Criteria 

- [x] I can see which dapps have permission to access my keys 
- [x] I can see an explanation of what it means i.e. these dapps have permission to access my keys and connect to my wallet
- [x] I can see instructions how to connect to a Vega dapp 
- [x] There is a way to see the dapps I could connect with (e.g. a link to https://vega.xyz/use )
- [x] When I have no connections I can see that and still see instructions on how to connect to a Vega dapp 
- [x] If I have the extension open on the Connections view AND I approve a request to connect to a dapp (and the connection is successful), the connections view should update to show the new connection

## Tasks

- [x] Detailed sketch
- [x] Visual design
- [ ] Implement UI and render the list of connections
- [ ] Let Matt know that the disconnection information via event handler needs to be handled his end :) 
- [x] Backend
    - [x] Expose the list of connections (#232)
    - [ ] Create event listener functionality
    - [ ] Emit the event on disconnect
- [ ] Integrate with backend
- [x] Write unit tests
- [x] Write end to end tests
- [x] Code review
- [x] Team verify acceptance criteria met
- [x] Exploratory QA testing 
- [x] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [x] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [x] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders 
- [ ] Release

## Design

[**Figma link** ↳](https://www.figma.com/file/rFlT1Ip2ot7Zfr2E5Is3Pd/Browser-Wallet?type=design&node-id=3395%3A3019&t=p6YMkRM9KfA82kCK-1)

<img width="1773" alt="View Connections" src="https://github.com/vegaprotocol/vegawallet-browser/assets/113684458/1981b89d-2c9e-4d5f-8cbd-ccd41e141a79">

## Sketch

![Image](https://github.com/vegaprotocol/vegawallet-browser/assets/46783148/0b4f1ec3-47d0-4276-92ec-a571d688504a)
