### ISSUE TITLE
Disconnect dapp (all keys) from wallet

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#132]
## Story 

As a wallet user 
I want to be able to disconnect a dapp connection from my wallet (revoking access to my keys)
So that I can be in control of who/what has access to my keys 

## Acceptance Criteria 

- [ ] I can choose to disconnect a dapp connection (and it's pre-approved status i.e.
- [ ] Disconnecting the dapp revokes access to all of my keys for that dapp / site 
- [ ] I can see visually the dapp has been removed from my list of connected dapps
- [ ] The dapp is informed of the disconnection via an event handler
- [ ] When I have disconnected, if I attempt to connect the wallet from the dapp again, I am asked to approve the connection 

## Tasks

- [x] Detailed sketch
- [x] Visual design
- [ ] Frontend tasks:
    - [ ] Implement UI
    - [ ] Integrate with backend
    - [ ] Write unit tests
- [ ] Backend tasks:
    - [x] Track active connections
    - [x] Disconnect active connections
    - [x] Delete connection state for dApp
     - [ ] Create event handler to tell dapp we have disconnected (We can use JSON-RPC notifications and expose a light event listener API on the injected vega object)
    - [ ] Optional: send notification to dApp about disconnect
    - [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release

## Design 
https://www.figma.com/file/rFlT1Ip2ot7Zfr2E5Is3Pd/Browser-Wallet?type=design&node-id=3395-2991&t=sPrsrgRZTK1oVjG5-0

![Image](https://github.com/vegaprotocol/vegawallet-browser/assets/46783148/ddf81c3d-d227-4e87-9eaf-c66b7779da84)

## Sketch

![Image](https://user-images.githubusercontent.com/46783148/236197321-60a87278-0de2-4bbc-a05f-0761f0d47020.png)
