### ISSUE TITLE
View transaction request (generic)

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#133]
## Story

As a user
I want to recognise transactions that are not orders or withdraw / transfer requests with at least the bear minimum information needed to proceed
So that I can continue my task (e.g. governing, staking)

## Acceptance criteria 

- [x] When the dapp requests a transaction with a key we don't know about, we don't see a request in the wallet but instead send an error back to the dapp
- [x] When the dapp requests a transaction type / or includes transaction details that we don't recognise, we don't present the transaction request in the wallet but provide an error to the dapp that feeds back that the transaction can not be processed
- [x] When the user opens the extension (or it has automatically opened) they can immediately see a transaction request
- [x] If the browser extension is closed during a transaction request, the request persists
- [x] For transactions that are not orders or withdraw / transfers, there is a standard template with the minimum information required i.e. 
-- [ ] Transaction title 
-- [ ] Where it is from  e.g. console.vega.xyz with a favicon
-- [ ] The key you are using to sign with a visual identifier
-- [ ] When it was received 
-- [ ] Raw JSON details
- [x] It is visually similar to other transaction types but essentially has less of the human readable detail(s) (design note)
- [x] I can copy the raw json to my clipboard
- [ ] When I try to submit a transaction to the wallet I've made during onboarding but have not "completed" onboarding, I cannot see the transaction request until I've completed onboarding (it is queued in the background) 

## Tasks

- [X] Detailed sketch
- [x] Visual design
- [x] Implement UI
- [x] Integrate with backend
- [x] Implement Authentication (encryption)
- [x] Write unit tests
- [x] Write end to end tests
- [x] Code review
- [x] Team verify acceptance criteria met
- [x] Exploratory QA testing 
- [x] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [x] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [x] Add story and A/Cs to spec doc 
- [x] Review with stakeholders 
- [x] Release

## Sketches
<img width="1089" alt="Screenshot 2023-05-02 at 09 29 04" src="https://user-images.githubusercontent.com/46783148/235617546-2eeb5b6d-81d6-4ca2-a945-ea957c1a3ea3.png">
