### ISSUE TITLE
EPIC: Finalise priority transaction receipts

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#134]
## Story

**This is the second pass of ALL priority transaction types, where key enrichments from market data will be performed, and the other previously defined ACs below should be checked and confirmed.**

As a wallet user
I want to immediately recognise where the submit order transaction has come from, what it's for and with which key I am signing it
So that I can get back to what I was doing as quickly as possible

## Priority Transaction Types

- [x] #524
- [x] #419 
- [x]  #418 
- [x]  #298 
- [x]  #420 
- [x]  #135 
- [x]  #415 
- [x]  #526
- [x] #444 

## Acceptance criteria 

Given on the individual tickets ..... broadly speaking:
- [ ] Anything that we built in the first pass that would be better expressed by enriching some data from the asset / market api should be done 

## Notes
- [ ] If you have more than one key, you have to have chosen the "right" key to start with in the dapp (not in the wallet)

## Tasks

- [x] Detailed sketch
- [x] Visual design
- [ ] Frontend
    - [ ] Implement UI 
    - [ ] Find a way to mock the data to be able to dev and test against 
- [ ] Backend tasks
    - [x] Extend the sample dapp / document (as part of this https://github.com/vegaprotocol/vegawallet-browser/issues/134) to have the ability to place orders - show the shape of the json data for orders
    - [x] Work out how the backend provides asset and market details
    - [ ] Caching the results
- [x] Integrate with backend
- [ ] Implement Authentication (encryption)
- [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders 
- [ ] Release

## Design 

**[Figma link ↳](https://www.figma.com/file/rFlT1Ip2ot7Zfr2E5Is3Pd/Browser-Wallet?type=design&node-id=3422%3A12231&t=p6YMkRM9KfA82kCK-1)**

<img width="1077" alt="image" src="https://github.com/vegaprotocol/vegawallet-browser/assets/89918817/b674ffe6-af34-4f88-a1a2-1f1d3c3ba695">

<img width="968" alt="image" src="https://github.com/vegaprotocol/vegawallet-browser/assets/89918817/8a9d0bf5-7cd7-4dc4-acd8-95d07404f3de">

## Sketches

Miro - https://miro.com/app/board/uXjVPUiQ2AE=/?moveToWidget=3458764552847131824&cot=14

<img width="2302" alt="Screenshot 2023-05-02 at 09 25 33" src="https://user-images.githubusercontent.com/46783148/235616849-f4920ead-249e-4dd2-b30c-1f578b9d1f62.png">

<img width="701" alt="Screenshot 2023-05-02 at 09 26 05" src="https://user-images.githubusercontent.com/46783148/235616958-4919e0ec-038b-463e-8789-25dba204ef9d.png">

**Comment by JonRay15** [comment]
The first pass on all these is now done.

This part is to add the market names / prices etc into the view. 

This is above the referral line
