### ISSUE TITLE
Transaction receipt 2nd pass: Withdrawals

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#135]
## Story

**As a** user who placed an withdrawal request 
**I want** to see all the key details of my transfer transaction in my browser wallet
**So that** I can be certain I am approving the correct transaction

## Acceptance Criteria

- [ ] The view contains the necessary data enrichment to provide
- [ ] Amount (with correctly formatted position decimals)
- [ ] From Key
- [ ] To Ethereum key

## Tasks

- [x] Detailed sketch
- [x] Visual design
- [ ] Frontend tasks:
    - [ ] Implement UI
    - [ ] Integrate with backend
    - [ ] Write unit tests
- [ ] Backend tasks:
    - [ ] TBC
    - [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release

## Sketch

<img width="235" alt="image" src="https://github.com/vegaprotocol/vegawallet-browser/assets/89918817/29878845-caa7-43d7-9c46-9d90528f4764">

<img width="711" alt="image" src="https://github.com/vegaprotocol/vegawallet-browser/assets/89918817/4b52bd13-6fe0-4914-8105-c6d9624373de">
