### ISSUE TITLE
Reject a transaction request

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#136]
## User Story

As a browser wallet user
I want to be able to reject a transaction request
So that I can prevent a transaction going through that I don't recognise as mine, or have changed my mind on / identified a mistake etc. 

## Acceptance Criteria

When I view a transaction request

- [x] I can choose to reject it

When I reject a transaction

- [x] The transaction does not get signed and the rejected status gets fed back to the dapp that requested it
- [x] After I have rejected it we revert to the next transaction if there's a queue OR we revert to the key view (start / home page)

## Tasks

- [X] Detailed sketch
- [x] Visual design
- [x] Implement UI
- [x] Integrate with backend
- [x] Write unit tests
- [x] Write end to end tests
- [x] Code review
- [x] Team verify acceptance criteria met
- [x] Exploratory QA testing 
- [x] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [x] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [x] Add story and A/Cs to spec doc 
- [x] Review with stakeholders 
- [ ] Release
