### ISSUE TITLE
Spam protection

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#141]
## Story 
 
As a team 
We want to implement spam protection for transactions
So that we can protect the network from abuse

## Acceptance Criteria 

- [ ] After user hits approve, there is spam protection in place to a set # of transactions within a period of time after which the user transaction submission is slowed
- [ ] As proof of work becomes harder, the user is shown a loading state to indicate that the approval is still in progress (and why maybe)
- [ ] If user has hit spam protection limit, they are informed of it 

## Tasks 

- [ ] Create a PoC for this based on what we understand so far
- [ ] Understand how core are testing this right now

Remaining tasks (TBC)

- [ ] Detailed sketch
- [ ] Visual design
- [ ] Frontend tasks:
    - [ ] TBC
    - [ ] Integrate with backend
    - [ ] Write unit tests
- [ ] Backend tasks:
    - [ ] TBC
    - [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release

## Background

There is a special API that we can ask 

There are notes written by Michael re A/Cs around spam protection that we might want to consider / weave in: 

Re: https://github.com/vegaprotocol/specs/blob/master/protocol/0072-SPPW-spam-protection-PoW.md

and https://vegaprotocol.slack.com/archives/C02KSKW6Y3F/p1664909617723239?thread_ts=1664886280.532059&cid=C02KSKW6Y3F

To reduce spam the wallet has to/may have to do some maths before submitting a transaction. This introduces a new set of errors and options that need to be handled by the wallet app and the Dapps.

handle transaction failure due to spam protection
handle wait time introduced by more complex math?
add option to pre-compute things in wallet (or not) see slack thread
give feedback on what is happening with spam protection? e.g. difficulty has increased.
