### ISSUE TITLE
Queue multiple transactions

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#142]
## Acceptance Criteria
- [x] If there are multiple transactions, they are queued one after the other and displayed after the one before it has been approved or rejected

## Tasks

- [ ] Explore and sketch
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

**Comment by dexturr** [comment]
Dupe?

**Comment by pennyandrews** [comment]
@dalebennett1992 we believe this is already done so would be great if you can just test and verify and ensure you are happy that there is suitable test coverage for it and it's covered in the specs etc. 🙏
