### ISSUE TITLE
View list of transactions (in the wallet)

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#143]
## Story 

As a wallet user 
I want to see a record of the transactions that I have "seen" in my browser extension 
So that I can check my transaction approval history

## Acceptance criteria 

- [ ] I can visually see where I would go to view my transactions (nav bar item)
- [ ] I can see a list of transactions - everything that makes it to the wallet screen
- [ ] I can see approved and rejected but not success and failure
- [ ] Each transaction has the relevant status label (approved, rejected)
- [ ] I can see what each transaction was i.e. there is a meaningful title 
- [ ] I can see an indication of where the transaction was requested from (either the dapp url or a visual cue / favicon) 
- [ ] I can see the key that signed the transaction (e.g. key name) 
- [ ] I can see when the transaction was received by the wallet (the time the request to sign and send was received)
- [ ] I can link from a list item to the transaction details (on block explorer)
- [ ] There is no limit to the transaction history viewable
- [ ] When there are no transactions there is an empty state that explains what would be here / why it's empty

We are using the generic transaction state for now (will add in custom views later)
If you've approved a transaction using the desktop app or CLI it's ok if that's not reflected here

## Tasks

- [x] Detailed sketch
- [x] Visual design
- [ ] Implement UI and render list of transactions
- [ ] Integrate with backend
- [ ] Backend
    - [ ] Add unlimited storage permission
    - [ ] Save all the transactions (and their meta data) we have seen 
    - [ ] Expose the api so the transaction list can be fetched
- [ ] Integrate with backend
- [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders 
- [ ] Release

## Design 

**[Figma link ↳](https://www.figma.com/file/rFlT1Ip2ot7Zfr2E5Is3Pd/Browser-Wallet?type=design&node-id=3389%3A8735&t=p6YMkRM9KfA82kCK-1)**

<img width="1474" alt="Transactions List" src="https://github.com/vegaprotocol/vegawallet-browser/assets/113684458/cbf4cebc-db7a-4d60-808a-cbbbe5ed34c7">

## Sketch

![Image](https://github.com/vegaprotocol/vegawallet-browser/assets/46783148/42bb89fd-a8e3-4639-b2b4-2096bf3ae7a2)

Miro: https://miro.com/app/board/uXjVPUiQ2AE=/?moveToWidget=3458764555290387347&cot=14
