### ISSUE TITLE
View (already confirmed or rejected) transaction details (in the wallet)

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#144]
## Story

As a user
I want to see the details of my completed transaction
So that I can check the details, share to prove it if needed and troubleshoot if something doesn't seem right

## Acceptance Criteria

- [ ] I can click on a transaction from the list and see the same details I'd seen to approve / reject when I first received them
- [ ] There is a way to navigate back to list of transactions
- [ ] I can see whether I confirmed or rejected the transaction
- [ ] There is a link to the block explorer page for that transaction 
- [ ] I can see the transaction hash and copy it to clipboard
- [ ] I can see what network it was on 
- [ ] I can see when I responded (confirmed or rejected)
- [ ] I can see when it was submitted to the network
- [ ] There is a backup, generic "Transaction couldn't be found" page
- [ ] If someone renames their key, the key would have the new name 
- [ ] I can still understand the historic order transaction when a market no longer exists e.g. we've found a way to store it

## Tasks

- [ ] Detailed sketch
- [ ] Visual design
- [ ] Implement UI
- [ ] Ensure the data can be shared between this and the transaction list
- [ ] Render the data on the page 
- [ ] Integrate with backend
- [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders 
- [ ] Release

## Design 

https://www.figma.com/file/rFlT1Ip2ot7Zfr2E5Is3Pd/Browser-Wallet?type=design&node-id=3261-871&t=2iJhdxAg7pulFpV3-0

![Image](https://github.com/vegaprotocol/vegawallet-browser/assets/46783148/cd8c418d-a334-41d0-8e3a-be2a6c67494b)

## Sketch

![Image](https://github.com/vegaprotocol/vegawallet-browser/assets/46783148/772e3164-ed21-47ce-ad8d-e6a0991866d7)

**Comment by JonRay15** [comment]
This is all covered by the ACs that Dex is now delivering on #143
