### ISSUE TITLE
Wallet version number (settings)

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#146]
## Story 

As a wallet user 
I want to understand the version # I am using 
So that I can trouble shoot should there be any issues 

## Acceptance Criteria

- [x] I can see the version # of the browser extension
- [x] I can see the feedback link
- [x] I can see a lock button and when I press it I am logged out and redirect to the login page

## Tasks

- [X] Detailed sketch
- [X] Visual design
- [x] Implement UI
- [x] Integrate with backend
- [ ] Implement Authentication (encryption)
- [x] Write unit tests
- [x] Write end to end tests
- [x] Code review
- [x] Team verify acceptance criteria met
- [x] Exploratory QA testing 
- [x] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [x] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [x] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders 
- [ ] Capture in Decision Log
- [ ] Release
