### ISSUE TITLE
Approve transaction request

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#147]
## User Story

As a browser wallet user
I want to be able to approve a transaction request
So that I can verify and complete the action I am trying to make on the vega dapp I'm using

## Acceptance Criteria

When I view a transaction request
- [x] I can choose to approve it

When I approve a transaction
- [x] The transaction gets signed and the approved status gets fed back to the dapp that requested it
- [x] After I have approved it we revert to the next transaction if there's a queue OR we revert to the key view (the front / homepage)

## Tasks

- [X] Detailed sketch
- [X] Visual design
- [x] Implement UI
- [x] Integrate with backend
- [x] Implement Authentication (encryption)
- [x] Write unit tests
- [x] Write end to end tests
- [x] Code review
- [x] Team verify acceptance criteria met
- [x] Exploratory QA testing 
- [x] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [x] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [x] Add story and A/Cs to spec doc 
- [x] Review with stakeholders 
- [x] Release
