### ISSUE TITLE
Confirm recovery phrase (stretch)

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#161]
## Story

As a wallet user
I want to validate I have "recorded" or saved the recovery phrase accurately 
So that I feel secure and confident to go ahead 

## Acceptance Criteria

- [ ] I can confirm I have written down / saved my recovery phrase by entering parts of it again in the UI
- [ ] There is a way to go back to see the full recovery phrase if I have written / saved it incorrectly 
- [ ] I can click to continue to the next step of onboarding once I've successfully entered the relevant parts of the phrase
- [ ] There is a way to understand if the details I've entered are incorrect e.g. highlight in red

## Tasks

- [X] Detailed sketch
- [x] Visual design
- [ ] Implement UI
- [ ] Integrate with backend
- [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release

## Initial sketch
<img width="1356" alt="Screenshot 2023-04-25 at 10 20 46" src="https://user-images.githubusercontent.com/46783148/234232913-9b6244b3-f682-4d0c-88f6-e79ff3be1377.png">

https://miro.com/app/board/uXjVPUiQ2AE=/?moveToWidget=3458764552609842514&cot=10

**Comment by JonRay15** [comment]
Below the referral line.
