### ISSUE TITLE
Run automated tests with Firefox

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#184]
## Tasks

- [ ] Find a way to locate extension endpoint consistently
- [ ] Configure web driver to conditionally run with firefox or chrome 
- [ ] Add package.json script
