### ISSUE TITLE
Understand if there's a queue of transactions

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#185]
## Story

As a wallet user 
I want to understand if there's a queue of transactions for me to approve / deny
So that I know what to expect as I interact with each

## Acceptance Criteria

- [ ] There is a way in the UI to understand how many transactions are in the queue
- [ ] I can see progress reflected in the UI as I make approvals / rejections (e.g. a number counting down)

## Tasks

- [ ] Detailed sketch
- [ ] Visual design
- [ ] Implement UI & Integrate with backend
- [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release
