### ISSUE TITLE
Visual feedback that my wallet was successfully created

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#194]
## Story

As a new wallet user
I want visual feedback when creating a new wallet 
So that I am assured everything has worked correctly

## Acceptance Criteria

- [x] I am given visual feedback that my wallet was successfully created

## Design 

**[Figma link ↳](https://www.figma.com/file/rFlT1Ip2ot7Zfr2E5Is3Pd/Browser-Wallet?type=design&node-id=3416%3A3649&t=a33xeS26G6IRXOIx-1)**

<img width="981" alt="Wallet-Success" src="https://github.com/vegaprotocol/vegawallet-browser/assets/113684458/d63c37a4-3a7e-42c6-bd8b-9c79966ab7b9">

## Sketches

![Screenshot 2023-05-10 at 10 35 03](https://github.com/vegaprotocol/vegawallet-browser/assets/46783148/fae2b7df-21ff-4007-b858-24e516468816)
![Screenshot 2023-05-10 at 10 27 46](https://github.com/vegaprotocol/vegawallet-browser/assets/46783148/fffe4aae-8b34-4c3e-81d4-748ed3d1dff9)
![Screenshot 2023-05-10 at 10 27 43](https://github.com/vegaprotocol/vegawallet-browser/assets/46783148/a790625c-dce5-4a43-baa9-1de887a4d653)
![Screenshot 2023-05-10 at 10 25 52](https://github.com/vegaprotocol/vegawallet-browser/assets/46783148/2a7d217c-85e6-4ad9-b1cc-f2c42329f8c1)

## Tasks

- [ ] Detailed sketch
- [ ] Visual design
- [ ] Implement UI & Integrate with backend
- [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release

**Comment by joellecharlotte** [comment]
Design attached and in Figma [here](https://www.figma.com/file/rFlT1Ip2ot7Zfr2E5Is3Pd/Browser-Wallet?type=design&node-id=3416%3A3649&t=a33xeS26G6IRXOIx-1) ↳ 

One for Successful Wallet **_Creation_** and one for Successful Wallet _**Import**_

<img width="981" alt="Wallet-Success" src="https://github.com/vegaprotocol/vegawallet-browser/assets/113684458/cad19039-9f57-4273-bf8a-81474f534339">
