### ISSUE TITLE
SPIKE: Show a name and icon for connection requests and connection list (not just a long IPFS link)

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/vegawallet-browser#200]
Is this an issue if we move to ETH links? 

Need to consider how this impacts the warning message you might get on installation

## Tasks

- [ ] Meeting with Barney and others to discuss the issue and agree what we could do about it
- [ ] Write up based on the outcome i.e. ticket the resulting work for us and other teams etc.

## Story

As a user
I want to see a friendly name and "good" icon of the website connecting / connected in your list of connections
So that I can easily understand, and trust, what I am connecting to

Related to #130 

## Proposal 1

It was proposed that the client API on connect wallet could take a name that the UI could show. I'd like to get @emilbayes thoughts on this and decide:

- [ ] What does this API look like
- [ ] Is there any other meta data we may allow the client to include to help with the UI that makes sense
- [ ] Is this optional or required
- [ ] If optional what does the UI do when not provided
- [ ] Are there any concerns we have around doing this

## Proposal 2

Start to publish assets with the console [releases](https://github.com/vegaprotocol/frontend-monorepo/releases) that would allow the browser wallet to connect to it.

## Proposal 3

Add "known apps" to the [well-known repo](https://github.com/vegaprotocol/well-known) whereby you can add some sort of TOML file and that tells the browsrer wallet that its legit. 

## Acceptance Criteria

- [ ] There is a favicon visible for the site I am connecting to / transacting with
- [ ] There is a user friendly name that I would recognise from interacting with the dapp I am connecting to / transacting with 
- [ ] The IPFS hash for the site / dapp is still available so that I can validate it, in a secondary way
- [ ] There is a way to click through to open the dApp

**Comment by JonRay15** [comment]
Jeremy suggested that if we published in console releases additional assets that pointed to the IPFS link and the version then we could do this.  Potentially that file could also include an icon.  He seemed fairly happy with that from a decentraliisation perspective (we already publish the IPFS links in that release, so its just making that more easily consumable by an app).

**Comment by JonRay15** [comment]
Per Barney on [slack](https://vegaprotocol.slack.com/archives/C8WS7M50E/p1692120745212349?thread_ts=1692120559.757189&cid=C8WS7M50E) we will soon have this vegaprotocol.eth domain which will be easier to look at.

Therefore this is descoped.  Will leave it in review until the rest of you have at least read it.
