### ISSUE TITLE
Implement Client: List keys api endpoints (happy path)

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-browser#21]
## The Chore

In order for a user to connect to a chosen dApp from the browser wallet we need to implement the keys API endpoint 

## Tasks - MVP scope/discovery to inc: 

- [ ] Time box to 1 week to get an basic e2e experience
- [ ] Demo the progress after one week and start to plan what needs to come next
- [ ] define what has been completed and what still is to be implemented

## Outcome

We want to do the MVP in order to be able to demonstrate this to get feedback on how to improve further
