### ISSUE TITLE
Document connect dapp integration

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-browser#211]
## Story

As a team
I want the other app teams (Console and Governance) to be able to self serve the integration work required to initiate the connection to the browser wallet
So that we minimise the work needed to support them AND can verify that third parties will be able to self serve integration with our wallet also for the apps they build on Vega  

## Acceptance Criteria

- [ ] There are docs written to support developers wanting to integrate their dapps to connect with the browser wallet 
- [ ] There are docs written covering what the transaction object looks like for sending transactions 
- [ ] The docs are available publicly and easily findable

## Tasks

- [ ] Decide where this documentation should live (vegwallet-browser repo? or docs site? or both?)
- [ ] Write docs
- [ ] Team verify acceptance criteria met
- [ ] Review with stakeholders (including devs from Console and Governance teams) 
- [ ] Release
