### ISSUE TITLE
Opt in to error reporting

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-browser#213]
## Story

As a wallet user
When I am using the browser extension for the first time
I want to be able to decide whether to opt in to automatic error reporting or not
So that I remain in full control of my privacy

## Acceptance Criteria

- [ ] I can see an explanation of what I am being asked to opt in/out to and why
- [ ] I can click a link to read more details about [vega user data policy ](https://vega.xyz/vega-wallet-user-data-policy/)
- [ ] I can opt in to reporting bugs and crashes
- [ ] I can opt out of reporting bugs and crashes
- [ ] If I have opted in and am using the wallet app, telemetry errors / analytics from frontend and backend are recorded / reported in Sentry
- [ ] If I have opted in and am using the wallet app, all keys are obscured and replaced with something appropriate in Sentry
- [ ] If I have opted out and am using the wallet app, telemetry errors / analytics are NOT recorded / reported in Sentry
- [ ] There is a way to change whether I want to opt in / out of error reporting later (e.g. in settings)

## Tasks

- [x] Detailed sketch
- [x] Visual design
- [ ] Frontend Tasks
    - [ ] Disable browser tracing
    - [ ] Frontend Implement (based on spike findings)
    - [ ] Plug into the backend
    - [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release

## Design

[**Figma link ↳** ](https://www.figma.com/file/rFlT1Ip2ot7Zfr2E5Is3Pd/Browser-Wallet?type=design&node-id=3395%3A7842&t=p6YMkRM9KfA82kCK-1)

![Image](https://github.com/vegaprotocol/vegawallet-browser/assets/46783148/6df8b8df-5c27-4eab-ae61-f718e3cd8f94)

[**Figma link ↳**](https://www.figma.com/file/rFlT1Ip2ot7Zfr2E5Is3Pd/Browser-Wallet?type=design&node-id=3395%3A8139&t=p6YMkRM9KfA82kCK-1)

![Image](https://github.com/vegaprotocol/vegawallet-browser/assets/46783148/8cc1e116-cb18-4d0e-be72-0b2793064b23)

## Notes

Tests written against desktop wallet A/Cs can be found here, in case useful to reuse / refer to [0001-WALL-003](https://github.com/vegaprotocol/specs/blob/master/user-interface/0001-WALL-wallet.md#0001-WALL-003)
