### ISSUE TITLE
Use the browser wallet on mainnet

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-browser#227]
## User Story

As a Vega team / Community member
I want to be able to try out the WIP version of the browser wallet on Mainnet (even though it's not really ready yet)
So that I can use it for real transactions for real money (at my own risk), kick the wheels on it and provide some feedback

## Notes

Every time we make a release, we make 4 builds:

- Chrome fairground (submitted to web store)
- Chrome mainnet (manually download from github)
- Firefox fairground (submitted to web store)
- Firefox mainnet (manually download from github)
- This will switch to the reverse when we launch our Beta version

## Acceptance Criteria

- [x] I can find a build of the browser wallet for mainnet
- [x] I can not switch from fairground to mainnet in the browser wallet UI
- [x] I can not update my network details or settings in the browser wallet UI
- [x] I am warned that the browser wallet is an early WIP build and I use it at my own risk

NB. we do not want to point tests at the mainnet version

## Tasks

- [ ] Detailed sketch
- [ ] Visual design
- [ ] Implement UI
- [ ] Create / update CI workflows
- [ ] Make network configuration configurable
- [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders 
- [ ] Release
