### ISSUE TITLE
Handle multiple connect/disconnect requests

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-browser#228]
## Story

As a user
If I make multiple connect / disconnect requests from a dapp to the wallet
I want xxx
So that xxx

## Acceptance Criteria

- [ ] I can
- [ ] I can
- [ ] I can

## Tasks

- [ ] Detailed sketch
- [ ] Visual design
- [ ] Implement UI & Integrate with backend
- [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release

## Notes

https://vegaprotocol.slack.com/archives/C052YCSFW6P/p1684915697676239

**Comment by dexturr** [comment]
Dupe

**Comment by pennyandrews** [comment]
@dalebennett1992 we believe this is already done so would be great if you can just test and verify and ensure you are happy that there is suitable test coverage for it and it's covered in the specs etc. 🙏

**Comment by dalebennett1992** [comment]
This already works and the e2e tests use this functionality
