### ISSUE TITLE
Communicate disconnection to dapps

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-browser#229]
## Story

As a user
If I disconnect the browser wallet from a dapp
I want xxx
So that xxx

## Acceptance Criteria

- [ ] I can
- [ ] I can
- [ ] I can

## Tasks

- [ ] Detailed sketch
- [ ] Visual design
- [ ] Implement UI & Integrate with backend
- [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release

## Notes

https://vegaprotocol.slack.com/archives/C052YCSFW6P/p1684828882667229
