### ISSUE TITLE
SPIKE: Transaction naming and the actions that get you there

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#231]
## The Spike

Most transaction names no longer map to the action you've taken in a dapp. The experience would be better if the names were improved where it makes sense to. This spike is to work out what, if anything, we want to do to improve the experience from dapp to wallet transaction whilst making sure anyone making their own dapps can still recognise the commands.

For example

**Action in UI:** Transaction title

**Place order:** OrderSubmission
**Cancel order:** OrderCancellation
**Edit order:** OrderAmendment
**Release funds:** WithdrawSubmission
**Remove stake:** UndelegateSubmission 
**Transfer:** Transfer(!)

## Questions we need to answer

- [ ] Where are the most surprising differences 
- [ ] Where are those justified
- [ ] Where can a change to the frontend be made to align more closely to the network command
- [ ] Where do we really think the command itself should be renamed 
- [ ] What are the rules - e.g. should the action "cancel" come first so that rather than a list of "Order X" you have a list of "Cancel order, Amend order etc."

## Tasks

- [ ] Work out the above, prioritising orders, transfers and withdrawals, governance transactions
- [ ] Create tickets for any agreed changes
