### ISSUE TITLE
Placeholder favicon + key imagery

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#248]
## Chore

This chore is to implement designs for placeholder for a connection request as it looks like an error with the question mark: 

- A dapp connection that doesn't have a favicon / image assigned (replacing the current question mark) 

And for transactions so that you can quickly, visually recognise what which type of transaction you are responding to. 

- A transaction with a vega key that is not in this wallet 
- A transaction with an Ethereum key (e.g. withdrawal) 

## Tasks

- [x] Update visual placeholder for connection requests
- [ ] Add warning text for when user is transferring to a key not controlled by this wallet
- [x] Update visual for Ethereum keys 

## Notes

```js

function toHex(str) {
    var result = '';
    for (var i=0; i<str.length; i++) {
      result += str.charCodeAt(i).toString(16);
    }
    return result;
  }

const getRemainder = (str) => {
   const h = toHex(str)
   return BigInt('0x' + h) % 6n
}

getRemainder('larvalabs.com') // => 3 so we pick the third colour

```

## Design

[**Figma link** ↳](https://www.figma.com/file/rFlT1Ip2ot7Zfr2E5Is3Pd/Browser-Wallet?type=design&node-id=3444%3A5568&t=3jvKtyuQuhE5WZsD-1)

<img width="1887" alt="Screenshot 2023-05-31 at 11 49 02" src="https://github.com/vegaprotocol/vegawallet-browser/assets/113684458/cd874592-8e13-4d4d-bbe2-b235397ffe80">

**Comment by pennyandrews** [comment]
I think this is already done, no?

**Comment by dexturr** [comment]
We said on this ticket we need to show a warning notification if the key is external
