### ISSUE TITLE
Open browser wallet in a new window

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-browser#259]
## Story

**As a** Browser Wallet User
**I want** the browser wallet to open in a pop-up window when there is a transaction for me to approve
**So that** I don't have to notice the dot and open the extension every time

## Acceptance Criteria

- [x] There is a way for me to open the browser wallet in a new window
- [ ] When the browser wallet is open in a new window, the window stays on top
- [ ] If I have a new window open, if there is a transaction for me to approve or reject this is shown in the new window 
- [ ] If I approve the transaction the new window stays open (on the last view I was on)
- [ ] If I reject the transaction the pop-up window stays open (on the last view I was on)
- [ ] If I resize the new window the browser wallet still looks good
- [ ] If I have the new window open but then open the extension pop up I see the same thing on both views 

Note: the two windows do not sync so if I approve a transaction in one window, it doesn't update to show as approved in the other window. However, if I approve the transaction in both windows it doesn't actually get approved twice (this is the same as Metamask behaviour)
    
## Tasks

- [ ] Detailed sketch (handling resizing window)
- [ ] Visual design (handling resizing window)
- [ ] Frontend tasks:
    - [ ] Implement UI
    - [ ] Integrate with backend
- [ ] Backend tasks:
    - [X] Implement behaviour
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release
