### ISSUE TITLE
Create privacy policy

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-browser#260]
## Chore

In order to get the browser wallet to pass the review and be accepted into the Chrome store, we need a privacy policy 

Slack thread https://vegaprotocol.slack.com/archives/C052YCSFW6P/p1685643158296049
https://developer.chrome.com/docs/webstore/program-policies/privacy/
Error code https://developer.chrome.com/docs/webstore/troubleshooting/#udp-prominent-disclosure

## Tasks

- [X] Understand the requirements
- [X] Write the policy (outline provided by Barney)
- [X] Add as page on vega.xyz (available only via direct URL)
- [ ] Supply link to the submission

Google Doc here 
https://docs.google.com/document/d/15MyArmvdpw9Rwz1anZN4MBXhhaQ1sgSKAbt2geT-1LA/edit#

Website URL
https://vega.xyz/vega-wallet-user-data-policy/
