### ISSUE TITLE
Return the same response payload from sending a tx as desktop wallet

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-browser#265]
## Chore

Matt has pointed out that we are not sending the same response payload as desktop wallet when sending a transaction. 

This is what he gets back from the wallet client:

```
{
    "result": {
        "receivedAt": "2023-06-05T10:29:45.503887-07:00",
        "sentAt": "2023-06-05T10:29:50.122231-07:00",
        "transactionHash": "ED8E3E88162E55C35F0853F9718C81649AC2A92954021B608508AA6C092ABC4C",
        "transaction": {
            "input_data": "CPCh3vzbjs66xgEQvrzcAco+SwpANGNiMDZjYTc0YzQ0YzJjNGFlYTUwMThjYTkxMDZiZDc3MWVlMGY4OTA0ZmE0MTI3YmNhYjYzN2JkMTc4MDFhMRjoByABKAM4Ag==",
            "signature": {
                "value": "95fef6f6be47c2f567c27e72840d0d44f29a1aaa494562aa2e3901f09343c0cccc76681881833690c38bf957a5d801c9034c31ccc49f6a1e2535b1222a11460a",
                "algo": "vega/ed25519",
                "version": 1
            },
            "From": {
                "PubKey": "70d14a321e02e71992fd115563df765000ccc4775cbe71a0e2f9ff5a3b9dc680"
            },
            "version": 3,
            "pow": {
                "tid": "d140a95fb2ee792f97e66cd86177237840344dd868ee9ec9d219f3ff5675a3a9",
                "nonce": 112711
            }
        }
    },
    "id": "Po6dtRVaMZC21r74mlta9"
}
```
This is what he's getting back from browser wallet (all the fields are ‘empty’ aside from txHash):

`{
    "success": true,
    "txHash": "33B3608EF89CDD64078BD64B2F3DC61AFC3082B9BF638828838D0B0E811EC533",
    "code": 0,
    "data": "",
    "log": "",
    "height": "0"
}`

The fields the dapps absolutely need us to include are txhash, receivedAt, sentAt and signature (signature being important because we use that to pair up a tx with a new order)

Follow this thread for any further development in the conversation https://vegaprotocol.slack.com/archives/C052YCSFW6P/p1685985550840109

## Tasks

- [ ] Implement changes
- [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Matt to verify we have met his criteria
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders 
- [ ] Release
