### ISSUE TITLE
Update secondary button style

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-browser#266]
## Chore

It was pointed out by Dale here https://vegaprotocol.slack.com/archives/C052YCSFW6P/p1685974082105409 that our secondary link style that is used across the dapps could be mistaken for a disabled button, rather than just a secondary one. We'd like to review the styling and see if there is an alternative treatment that would stay in keeping with the brand but avoid this potential misunderstanding and work across all the dapps. 

Joëlle has since revised this and we were all happy so it just needs to be implemented?

## Tasks

- [x] Explore alternative style options for secondary CTAs across Vega Dapps
- [x] Share with FE leads and decide on solution
- [ ] Implement UI change in browser wallet
- [ ] Test and verify
- [ ] Release

## Design

[Figma documentation here ↳](https://www.figma.com/file/EaFndX7sV9CgZOdsE2Ilqp/dApp-Components?type=design&node-id=720%3A10542&t=3N422pfgsr7xdNw1-1)
 
<img width="859" alt="Secondary-Button" src="https://github.com/vegaprotocol/vegawallet-browser/assets/113684458/072e7d87-8d7c-4ed8-9af5-0a3537678f7b">

**Some examples of the new Secondary Button in situ**

<img width="360" alt="01 Connect@2x" src="https://github.com/vegaprotocol/vegawallet-browser/assets/113684458/dda49652-7173-454d-8e3d-6d1427c38376">
<img width="360" alt="03 Add a Wallet@2x" src="https://github.com/vegaprotocol/vegawallet-browser/assets/113684458/bbd7326a-daf4-4002-9748-f9ed5ea7f54c">
<img width="360" alt="03 2 Confirm Disconnect@2x" src="https://github.com/vegaprotocol/vegawallet-browser/assets/113684458/a4aff942-8c0e-419b-bfe7-894c2fecc26e">
