### ISSUE TITLE
Real-time validation on input fields

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-browser#267]
## Story

**As a** browser wallet user
**I want** to see realtime feedback on the validity of the content I am entering in input fields 
**So that** I know if I am entering something valid or not as quickly as possible and can correct it as I go, rather than waiting to hit submit and then finding out I have missed something

## Acceptance Criteria

- [ ] I can see feedback on the validity of the content I am entering into an input field as I type (or equivalent)
- [ ] I can NOT submit until I have entered valid content (i.e. the submit button is disabled)

NB. The second A/C in the list would not be the case where we are just offering guidance on content i.e. setting a password, only where there are black and white criteria an entry has to meet to be able to be submitted successfully

## Tasks

- [ ] Detailed sketch (if needed)
- [ ] Visual design (if needed)
- [ ] Frontend tasks:
    - [ ] Implement UI
    - [ ] Integrate with backend
    - [ ] Write unit tests
- [ ] Backend tasks:
    - [ ] TBC
    - [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release

**Comment by joellecharlotte** [comment]
Linking to the [Input Field Documentation](https://www.figma.com/file/EaFndX7sV9CgZOdsE2Ilqp/dApp-Components?type=design&node-id=807%3A9723&t=3N422pfgsr7xdNw1-1) as it may be useful. The default, hover, focused, error and disabled states are shown. 

Might be something missing...

![Input-Field-Documentation](https://github.com/vegaprotocol/vegawallet-browser/assets/113684458/bf8f8b8c-a7e8-447b-b3f8-ce16da384212)
