### ISSUE TITLE
Improve the integration of Browser Wallet documentation into wider Wallet docs

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-browser#270]
## Chore

Emil has created the core browser wallet documentation and this is in a [docs PR](https://github.com/vegaprotocol/documentation/pull/629) based on this [issue](https://github.com/vegaprotocol/vegawallet-browser/issues/211). This documentation is sufficient to enable Console team to integrate the frontend apps with the browser wallet, but Candida has requested that we go a little further to improve the overall structure of Wallet related docs and how the browser wallet content fits within that.  

## Tasks

- [ ] Review all Wallet docs content and structure
- [ ] Sketch / propose changes and discuss with browser wallet and docs teams
- [ ] Implement structure changes
- [ ] Review and refine content to fit with new structure
- [ ] Check and verify
- [ ] Release

**Comment by JonRay15** [comment]
Think this got dropped back onto the backlog because its not clear to me that we should be dedicating browser wallet time to look at this given other priorities.

**Comment by JonRay15** [comment]
Should be me and Emil rather than Dex

**Comment by JonRay15** [comment]
Candida does not want this ..... ignore
