### ISSUE TITLE
Percy

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-browser#288]
## Chore

Get Percy set up for visual testing

## Tasks

- [ ] Work out what we need - could just start with 10k screenshots per month
- [ ] Speak to Percy peeps to get a cost
- [ ] Get cost approved with Rebecca
