### ISSUE TITLE
Synchronise (and tidy up) open wallet windows

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-browser#293]
## Story

**As a** wallet user
**I want** all my open browser windows to synchronise 
**So that** I can keep track of where I'm at with my transactions and what is remaining for me to action

## Acceptance Criteria

When I have multiple wallet windows open
- [ ] If I am asked to approve a transaction can 
- [ ] I can
- [ ] I can

## Tasks

- [ ] Detailed sketch
- [ ] Visual design
- [ ] Frontend tasks:
    - [ ] Implement UI
    - [ ] Integrate with backend
    - [ ] Write unit tests
- [ ] Backend tasks:
    - [ ] TBC
    - [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release
