### ISSUE TITLE
Handle versioning of the wallet to support different transaction types

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/vegawallet-browser#297]
Emil to refine the ticket to be more specific to browser wallet

## The Chore

In preparation for **Deployment 1** we need to upgrade the browser wallet to use the latest version of the wallet backend, check and verify that it works plug and play with the new transaction types and prepare to release.

## Tasks

- [ ] Upgrade the browser wallet to use the latest version of the protos
- [ ] Add A/Cs and test coverage to ensure the following transactions work as expected:
    - [ ] Successor Markets  - updated order transaction supported
    - [ ] Governance Initiated Transfers - new transaction type supported
    - [ ] Stop Orders - new transaction types supported (Submit, Amend, Cancel)
    - [ ] Iceberg Orders  - updated order transaction supported (Submit, Cancel)
- [ ] Deploy to Fairground
- [ ] Test in Fairground
    - [ ] Run automated tests of existing functionality
    - [ ] Manual smoke testing of existing functionality
    - [ ] Manually test new features (as applicable)
- [ ] Deploy to Mainnet
 - [ ] Test in Mainnet
    - [ ] Manual smoke testing of existing functionality
    - [ ] Manually test new features (as applicable)
