### ISSUE TITLE
Transaction receipt 2nd pass: Submit Stop Order

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/vegawallet-browser#298]
## Story

**As a** user who placed a Stop order
**I want** to see all the key details of my order transaction and changes in my browser wallet
**So that** I can be certain I am approving the correct transaction

## Acceptance Criteria

- [ ] I can see a human readable 'receipt style' view of the key details when I am requested to approve / reject a Submit Order transaction
- [ ] The view contains the necessary data enrichment to provide
  - [x] Market name
  - [x] Direction
  - [x] Size (with correctly formatted position decimals)
  - [x] Price (with correctly formatted asset decimals)
    - [x] Limit order handling
    - [x] Market order handling
    - [x] Pegged order handling
  - [x] Time in force
  - [x] Post / reduce only if applicable
  - [x] Trigger price 
  - [x] Trigger direction
  - [x] Expiry
  - [x] OCO if applicable

## Tasks

- [x] Detailed sketch
- [x] Visual design
- [ ] Frontend tasks:
    - [ ] Implement UI
    - [ ] Integrate with backend
    - [ ] Write unit tests
- [ ] Backend tasks:
    - [ ] TBC
    - [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release

## Sketch

We dont have Figma for the stop order ... you will have to freestyle based on the regular submit order!

<img width="194" alt="image" src="https://github.com/vegaprotocol/vegawallet-browser/assets/89918817/0edff9aa-ca70-4f7d-b144-8e2a115b637f">

To be honest most of the layout is probably already there from the first pass .... we just need the same enrichments as on the submit order ... including all the various prices.

**Comment by JonRay15** [comment]
Superseded

**Comment by JonRay15** [comment]
This is already done
