### ISSUE TITLE
Basic (manual) synchronisation of open wallet windows "Viewing in another window"

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#315]
## Story

**As a** wallet user
**I want** to never have a situation where I'm confused by "which" wallet window is my active session
**So that** I can quickly approve / reject transactions (or whatever I was trying to do!) 

## Acceptance Criteria

- [ ] When I have popped the wallet into a separate window and click to open the extension again, the window with my wallet it in comes to the front
- [ ] If I close the wallet window, and click to open the extension again, it opens in a popover

## Tasks

- [x] Sketch 
- [x] Design
- [ ] Frontend tasks:
    - [ ] Implement UI
    - [ ] Integrate with backend
    - [ ] Write unit tests
- [ ] Backend tasks:
    - [ ] TBC
    - [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release

**Comment by ckpringle** [comment]
Needs rebasing for Firefox issue
