### ISSUE TITLE
Update for v0.76 of the protos

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/vegawallet-browser#330]
## The Chore

Update the protos to v0.76

## Tasks

- [x] Update to support the addition of the new proposal types
  - [x] New spot market
  - [x] Update spot market
  - [x] Suspend / resume market
