### ISSUE TITLE
Link from key to filtered explorer view (party)

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#334]
## Story

**As a** user
**I want** to easily see my keys transactions
**So that** I can check if the transaction was successful or not

## Acceptance Criteria

- [x] From a key, there is a link from a key to block explorer filtered transaction view e.g. https://explorer.vega.xyz/parties/c1d9a39e5148b14d694020572cb591a8af971b9c5a4a185f3afa47bd9247c0da
- [x] The link from a key is differentiated from the copy "button" i.e. I can click copy to copy the ID or click the link and arrow to view in explorer

## Tasks

- [x] Detailed sketch
- [x] Visual design
- [x] Frontend tasks:
    - [x] Implement UI
    - [x] Integrate with backend
    - [x] Write unit tests
- [x] Backend tasks:
    - [x] TBC
    - [x] Write unit tests
- [x] Write end to end tests
- [x] Code review
- [x] Team verify acceptance criteria met
- [x] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [x] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release

## Sketch
<img width="559" alt="Screenshot 2023-07-05 at 12 33 54" src="https://github.com/vegaprotocol/vegawallet-browser/assets/46783148/4766939d-f92b-43b8-a1d4-c7b7f202992e">
