### ISSUE TITLE
Change name and icon for fairground / mainnet versions

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#341]
## Story

**As a** user
**I want** to be able to quickly check which extension I have installed for which version mainnet or fairground
**So that** I know what I have / am testing and can avoid confusion if I do have both installed at the same time

## Acceptance Criteria

- [ ] Mainnet has a black icon 
- [ ] Fairground has the existing icon 
- [ ] Network is appended to the extension name `Vega Wallet - Mainnet` `Vega Wallet - Fairground`

## Tasks

- [ ] Design / export and attach assets (make it work on dark mode / light more i.e. does it need a stroke?)
- [ ] Frontend tasks:
    - [ ] Implement UI
    - [ ] Integrate with backend
    - [ ] Write unit tests
- [ ] Backend tasks:
    - [ ] TBC
    - [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release
