### ISSUE TITLE
Update protos to support core changes (or not!)

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-browser#342]
## Tasks

- [ ] Run script to identify the core changes and understand whether they would impact use of the browser Mainnet if we do update, or Fairground if we don't update
- [ ] Decide what to do
- [ ] Update documentation / readme etc. to manage expectations based on what we find and decide
