### ISSUE TITLE
Make browser wallet look better for the mobile browsers it already works with

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-browser#348]
Barney discovered that the browser wallet works on some of the more obscure mobile browsers i.e. Orion but with some small layout issues. As a team we would like to do a very small amount of work to make the wallet extension look better for those mobile browsers that it works with. 

THIS IS NOT WORK TO MAKE BROWSER WALLET WORK ON MOBILE ACROSS THE BOARD, THERE IS SEPARATE WORK PLANNED FOR THIS TO COME LATER. 

## Tasks

- [ ] Establish and agree a list of mobile browsers that the wallet works in to understand the scope of work and testing
- [ ] Make the necessary visual / layout improvements to make it look acceptable in each of the agreed browsers
- [ ] Test and verify (at least manually, we might not want to take on the work at this point to automate the visual testing)

**Comment by JonRay15** [comment]
Kicking this to backlog because relative to the priorities for this sprint (ie. launching, and getting snaps working) this is not something we should be looking at any futher. Revisit after launch.

**Comment by JonRay15** [comment]
There is also info in console ticket #4567 which may help with this.

But basically we think Console works on mobile, so the question is can we run the wallet in iOS / Android so it supported mobile trading - we think Console does already.

**Comment by JonRay15** [comment]
Killing and replacing with a proper mobile spike.
