### ISSUE TITLE
Calls to action to trade or govern (or check out other dapps) to "continue" the journey

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#355]
## Story

As a user
I want to easily go to the next step in my Vega onboarding i.e. trade, govern or explore other Vega dapps
So that I can get "doing" as fast as possible regardless of where I started from 

## Acceptance Criteria

- [x] There is a way to go to console from the wallet i.e. a link / cta 
- [x] There is a way to go govern from the wallet i.e. a link / cta 
- [x] There is a way to view other Vega dapps i.e. a link / cta 
- [x] There is a way to see what's linked to e.g. a hover state with the dapp name 

## Tasks

- [x] Detailed sketch
- [x] UI Design inc. working out how to manage the actions should they be across app in a toolbar or something else?
- [x] Frontend tasks:
    - [x] Implement UI
    - [x] Write unit tests
- [ ] Write end to end tests
- [x] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release

## Sketch

![Image](https://github.com/vegaprotocol/vegawallet-browser/assets/46783148/5e394a94-63b3-43ba-8817-6ed660ee4f98)
