### ISSUE TITLE
SPIKE: How can we best enable depositing assets

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#357]
## The Spike
How can we make depositing funds on Vega, relevant to the market you want to trade, faster and easier across touchpoints?

## Questions we need to answer

- [ ] How to make completing a deposit a more joined up experience between wallet and console
- [ ] How to make it clear you are only "putting money in" in order to trade on Vega
- [ ] What's needed to give people confidence enough to complete a deposit 
- [ ] What if deposit was a standalone separate tool?
- [ ] Can we remove the need to connect my wallet to a dapp before making a deposit?
- [ ] What's the ideal experience e.g. is it just to link the wallet and dapp with some handholding or does it involve a separate deposit tool that you can easily launch from the wallet

## Tasks

- [ ] 
- [ ]
- [ ] 

## Notes

- Considering a way to understand how you get assets onto Vega e.g. "Deposit assets from your Ethereum wallet" 
- And why e.g. "Why can't I just send assets directly? Vega is its own blockchain, faster and more efficient than Ethereum - perfect for traders. Because of this, depositing an asset requires an extra step, verification against the Vega smart contract."
- Expect a link as a minimum to a deposit form on Console, but could be that a standalone deposit dapp is the best experience to start the deposit journey from the wallet, or something else
- I can understand that to trade, I need to deposit the correct asset for the market I am trading

**Comment by ckpringle** [comment]
Outcome tickets

#406 
https://github.com/vegaprotocol/frontend-monorepo/issues/4357

**Comment by ckpringle** [comment]
And technically there is no way to connect to any ethereum wallet from within our extension, each would need a custom solution so it makes sense this work is outside of the wallet development.
