### ISSUE TITLE
List compatible browsers

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#360]
## Chore

This chore is to document browser wallet's **compatible browsers (tested)** and **might work on (not thoroughly tested)** experimental browsers, and agree where to place the content e.g. docs? github readme?

> We support Firefox, Chrome
> 
> It might work on these 
> * Brave
> 
> But we've not tested against it. Last updated 28 Jul 2023

## Tasks

- [ ] Consider if we expand the CI run to actually do some level of testing agains the other Chrome browsers etc but only if it's really easy otherwise _just_ add the documentation
- [ ] List the browsers somewhere in the documentation
- [ ] Agree where to publish and link from
- [ ] Publish
