### ISSUE TITLE
Understand the number of steps for wallet creation

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#365]
## Story

As a user 
I want to understand visually how many steps there are to create my wallet 
So that I understand at a glance that this will be quick and simple 

## Acceptance Criteria

- [ ] There is a visual cue of the number of steps involved in creating or importing a wallet for the first time e.g. a bar at the top of the screen 
- [ ] As I progress through creating a wallet, the visual cue updates to show progress step by step up until wallet creation or import is successful

## Tasks

- [ ] Detailed sketch
- [ ] Visual design
- [ ] Frontend tasks:
    - [ ] Implement UI
    - [ ] Integrate with backend
    - [ ] Write unit tests
- [ ] Backend tasks:
    - [ ] TBC
    - [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release

**Comment by JonRay15** [comment]
Below the referral line
