### ISSUE TITLE
Password security feedback

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#366]
## Story

As a Trader
I want to understand whether the password I'm creating is secure
So that I am encouraged to set a secure password

Feedback is to be taken as guidance / suggestion to improve, but does not prevent creation of any password 

## Acceptance Criteria

- [ ] During password creation, there is a way to understand whether the password I have created is secure or not 
- [ ] I can set my password to anything, regardless of the feedback I am given on how secure or not it is
- [ ] There is validation against single spaces (or just spaces at all) being a valid password 

## Tasks

- [ ] Detailed sketch
- [ ] Visual design
- [ ] Frontend tasks:
    - [ ] Implement UI
    - [ ] Write unit tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release

## Sketch

![Image](https://github.com/vegaprotocol/vegawallet-browser/assets/46783148/3288c90d-86d9-472b-99aa-932727d8a33f)

## Design

[Figma link here](https://www.figma.com/file/rFlT1Ip2ot7Zfr2E5Is3Pd/Browser-Wallet?type=design&node-id=3878%3A9198&mode=design&t=BKL6QEZkRetFg8n2-1) ↳ 

<img width="2376" alt="Screenshot 2023-07-20 at 15 45 26" src="https://github.com/vegaprotocol/vegawallet-browser/assets/113684458/96cafa55-0065-48dc-9a78-dd7a949f8859">

## Notes

Emil would not place any policy but only advise using something like the suggested strength meter. Technically the password is combined with a randomly generated nonce/salt, put though a key derivation function called Argon2id, probably with 10 iterations over 256MB memory. I can perhaps defer to NIST password guidelines https://pages.nist.gov/800-63-3/sp800-63b.html#memsecret

pages.nist.gov
[NIST Special Publication 800-63B](https://pages.nist.gov/800-63-3/sp800-63b.html#memsecret)
NIST Special Publication 800-63B

They suggest a min of 8 chars for memorised secret authenticators but most importantly that the user is informed about the suitability of the password (technically what is the entropy). Ie ‘aaaaaaaa’ is clearly more repetitive than ‘oranges!’

https://github.com/dropbox/zxcvbn/tree/master#usage
