### ISSUE TITLE
Notify of connection and transaction requests e.g. auto open and close

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#368]
## Story

As a Browser Wallet User
I want the browser wallet to open when there is a transaction for me to approve and close after I've approved or rejected it
So that I don't have to notice the dot and open the extension every time

- When I submit a connection request from a dapp, I expect my browser wallet plugin to come to view automatically, rather than have to go find it.
- When I submit a transaction request from a dapp, I expect my browser wallet plugin to come to view automatically, rather than have to go find it.

## Acceptance Criteria

Connection:
- [x] The browser wallet opens in a pop-up window when there is a connection request
- [x] If I close the pop-up window the connection persists
- [x] If I approve the connection the pop-up window closes
- [x] If I reject the connection the pop-up window closes

Transaction:
- [x] The browser wallet opens in a pop-up window when there is a transaction request
- [x] If I close the pop-up window the transaction persists
- [x] If I approve the transaction the pop-up window closes
- [x] If I reject the transaction the pop-up window closes

## Tasks

- [x] Detailed sketch
- [x] Visual design
- [x] Frontend tasks:
    - [x] Implement UI
    - [x] Integrate with backend
    - [x] Write unit tests
- [ ] Backend tasks:
    - [ ] TBC
    - [] Write unit tests
- [x] Write end to end tests
- [x] Code review
- [x] Team verify acceptance criteria met
- [x] Exploratory QA testing 
- [x] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [x] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [x] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release
