### ISSUE TITLE
Add legal disclaimer

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#369]
## Chore
Add legal disclaimer bullets to the Vega Wallet browser extension. 

Dependent on #370 

## Tasks

- [x] Think about how we handle mainnet v fairground as the disclaimer is only relevant for mainnet 
- [x] Work out where to place content 
- [x] Finalise content (see the part under [Disclaimer](https://docs.google.com/document/d/1kYqvTsGG3SwbUDvLDXoTgw3r0rM_hQo4DVkOKBtabLU/edit) in this doc.... EXCLUDING "Spot an issue? Provide feedback here.....)
- [ ] Make changes to testnet version
- [ ] Make changes to mainnet version
- [ ] Test

## Sketch

Mainnet 

![Image](https://github.com/vegaprotocol/vegawallet-browser/assets/89918817/56e9b01f-ffaf-4748-855e-75b69e99c6a7)

Testnet

![Image](https://github.com/vegaprotocol/vegawallet-browser/assets/89918817/77d0380e-0f4a-4223-8282-0037c7ce7a31)

**Comment by JonRay15** [comment]
Lets add a tick box that you have to tick before it will let you click get started 

Remove the create / import cos that changes the flow.
