### ISSUE TITLE
Governance Initiated Transfer Proposal transaction receipt view

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-browser#373]
## Story

As a wallet user
I want to immediately recognise the details in the transaction approval request as the Government Initiated Transfer Proposal I just Created or Cancelled, what it's for and with which key I am signing it with
So that I can get back to what I was doing as quickly as possible

## Acceptance criteria

- [ ] When the dapp requests a transaction with a key we don't know about, we don't see a request in the wallet but instead send an error back to the dapp
- [ ] When the dapp requests a transaction type / or includes transaction details that we don't recognise, we don't present the transaction request in the wallet but provide an error to the dapp that feeds back that the transaction can not be processed
- [ ] When the user opens the extension (or it has automatically opened) they can immediately see the transaction request
- [ ] If the browser extension is closed during a transaction request, the request persists
- [ ] The key the transaction defaults to is the one connected to the dapp
- [ ] The primary information for Governance Initiated Transfer Proposal transactions is human readable (think of it as a receipt view of the proposal) e.g.
-- [ ] Fields TBD
- [ ] Transaction title is as defined in the network 
- [ ] If data returned is a default value, we don't display it
- [ ] I can see when the transaction was received
- [ ] There is a way to view and copy the raw json to my clipboard

## Notes
- [ ] If you have more than one key, you have to have chosen the "right" key to start with in the dapp (not in the wallet)

## Tasks

- [ ] Detailed sketch
- [ ] Visual design
- [ ] Implement UI
- [ ] Backend
    - [ ] Provide the api to get the asset data
- [ ] Integrate with backend
- [ ] Implement Authentication (encryption)
- [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders 
- [ ] Release

## Additional details / background info

**Comment by JonRay15** [comment]
This is nonsense .... a governance initiated transfer is initiated by .... goverance... so there is no TX to approve.
