### ISSUE TITLE
Add Submit & Cancel Iceberg Order details to receipt view of transaction requests

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-browser#375]
## Story

As a wallet user
I want to immediately recognise the details in the transaction approval request as the Iceberg Order I just Submitted
So that I can get back to what I was doing as quickly as possible

## Acceptance criteria

- [ ] The primary information for Order transactions is human readable (think of it as a receipt view of the proposal) and includes the fields related to Iceberg orders e.g.
    - [ ] That it is an Iceberg Order
    - [ ] Maximum peak size
    - [ ] Minimum peak size

## Tasks

- [ ] Detailed sketch
- [ ] Visual design
- [ ] Implement UI
- [ ] Backend
    - [ ] Provide the api to get the asset data
- [ ] Integrate with backend
- [ ] Implement Authentication (encryption)
- [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders 
- [ ] Release

## Additional details / background info

**Comment by dexturr** [comment]
Closing as duplicate #376
