### ISSUE TITLE
List connections by most recently connected

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-browser#385]
## Story

As a Trader
I want to see the most recently connected dapps listed first on the connections view
So that I can easily understand my connections

## Acceptance Criteria

- [ ]  I can see my connections listed with the most recently connected at the top of the list (can update the existing test to include this)
- [ ] Reconnecting a dapp updates the last connected time/date
- [ ] I can see the date/time I last connected to each dapp in the list
- [ ] I can click on the connected dapp and be taken to that dapp

## Tasks

- [ ] Detailed sketch
- [ ] Visual design
- [ ] Frontend tasks:
    - [ ] Implement UI
    - [x] Integrate with backend
    - [x] Write unit tests
- [x] Backend tasks:
    - [x] Update last connected every time we connect to a dapp
    - [x] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release

**Comment by JonRay15** [comment]
Currently this appears backwards

We need to reverse the sort order.

**Comment by JonRay15** [comment]
There is another ticket which we will move into TODO
