### ISSUE TITLE
Finalise web store content and screenshots

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#402]
## Chore

Add screenshots to web stores as part of release.

## Tasks

- [x] Finalise [content](https://docs.google.com/document/d/1kYqvTsGG3SwbUDvLDXoTgw3r0rM_hQo4DVkOKBtabLU/edit) to go on stores for both versions
- [x] Provide screenshots
- [ ] Carry out #430 to update webstores for mainnet
- [ ] Carry out #469 to update webstors for testnet

### Required Screens 

![Image](https://github.com/vegaprotocol/vegawallet-browser/assets/89918817/8564d23c-0232-48ff-abce-a65e23228510)
![Image](https://github.com/vegaprotocol/vegawallet-browser/assets/89918817/933bcac1-6274-4e62-b67e-442c3ba93a42)
![Image](https://github.com/vegaprotocol/vegawallet-browser/assets/89918817/c7e0bb80-b3f6-4b21-a676-2245e9018c24)
![Image](https://github.com/vegaprotocol/vegawallet-browser/assets/89918817/329a7aa2-4728-4694-a41e-9c756da0d107)
![Image](https://github.com/vegaprotocol/vegawallet-browser/assets/89918817/ff77843b-20d9-4ba4-8a8f-e4a7d4f0bcca)
![Image](https://github.com/vegaprotocol/vegawallet-browser/assets/89918817/4cda59b3-f1e9-4995-9eab-36b32cf4dc1a)

**Comment by JonRay15** [comment]
Moving this to in review because the actual tasks to execute these changes for mainnet and testnet are now tracked seperately.
