### ISSUE TITLE
Auto open browser extension on install

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#403]
## Story

As a new Vega user
I want the browser wallet to open automatically once installed (like Metamask does) 
So that I know what to do next in my onboarding (create / import a wallet etc.).

**NB. This should literally just be once you install it (regardless of what site you're on) we automatically pop out the window.**

The stuff about Console making it pop back up shoudl be handled by Console. 

## Tasks

- [ ] Identify what is technically possible to trigger on install (open extension, open wallet in new window ??)
- [X] Sketch
- [ ] Frontend tasks:
    - [ ] Implement UI
    - [ ] Integrate with backend
    - [ ] Write unit tests
- [ ] Backend tasks:
    - [ ] TBC
    - [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release

## Notes
<img width="1977" alt="Screenshot 2023-07-19 at 15 47 52" src="https://github.com/vegaprotocol/vegawallet-browser/assets/46783148/a13eb6ca-f942-47c3-9547-a04372a1bf52">

**Comment by dexturr** [comment]
https://stackoverflow.com/questions/5745822/open-a-help-page-after-chrome-extension-is-installed-first-time/24429523#24429523

**Comment by JonRay15** [comment]
Option 1 has been agreed with Barney, so we should proceed with this

**Comment by dexturr** [comment]
Closed by #open

**Comment by dexturr** [comment]
Closed by #516
