### ISSUE TITLE
SPIKE: Reducing steps in wallet onboarding

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#405]
## The Spike

Can we reduce the number of steps in wallet onboarding i.e. get started, through the disclaimer, create password, create / import, recovery phrase, confirmation and success?

## Questions we need to answer

- [ ] Can the steps to get started and create a wallet or import be combined?  
- [ ] What are the technical implications of the change?
- [ ] Is there anything else we can do to reduce the steps here?

## Tasks

- [ ] Review what we have right now
- [ ] Research technical options to enable create / import before password creation 
- [ ] Make a decision on whether this is worthwhile 
- [ ] Write any resulting tickets

## Notes

- We wanted to create an encrypted store before you create or import a wallet - but there could be a way to do it that doesn't need a password to already have been created
- Alternatively import / create and set password could be handled at the same
