### ISSUE TITLE
Guided standalone deposit 

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#406]
## Story

**As a** new user
**I want** an easily understood way to deposit the right assets in order to trade
**So that** I feel confident in depositing the right assets and am ready to trade more quickly

## Acceptance Criteria

- [ ] There is a clear call to action to deposit from the wallet 
- [ ] When I have no funds in my wallet already, I can see an explanation of how to deposit i.e. I need to deposit funds from an Ethereum wallet 
- [ ] If I don't have an Ethereum wallet, there is a link to get one [https://ethereum.org/en/wallets/find-](https://ethereum.org/en/wallets/find-wallet/)
- [ ] There is a stepped flow to connect my Ethereum wallet 
- [ ] I can

## Tasks

- [ ] Detailed sketch
- [ ] Visual design
- [ ] Frontend tasks:
    - [ ] Implement UI
    - [ ] Integrate with backend
    - [ ] Write unit tests
- [ ] Backend tasks:
    - [ ] TBC
    - [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release
