### ISSUE TITLE
View assets per key

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#408]
## Story

**As a** user
**I want** to see my funds
**So that** I can verify my deposit is successful in more than one place, and easily check what is in which key

## Acceptance Criteria

Unit Testing:
- [x] From the main wallets screen I can click on a key to be shown the list of assets on that key
- [x] The "pills" shown link to that market in Console
- [x] There is a warning to remember that if I hold an open position the balance / totals may not be accurate as is constantly changing

E2e testing:
- [x] I can see the balance of each (the sum across ALL account types)
- [x] There is a button / icon that allows me to expand the view to show the breakdown of all non-zero accounts for that asset
- [x] There is a way to switch between keys (or to easily navigate back to the keys page to achieve this)
- [x] When switching, I can see key name, key icon and key address (truncated)

## Tasks

- [x] Detailed sketch
- [x] Visual design
- [x] Frontend tasks:
    - [x] Implement UI
    - [x] Integrate with backend
    - [x] Write unit tests
- [ ] Backend tasks:
    - [ ] TBC
    - [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release

## Sketches

Miro: https://miro.com/app/board/uXjVPUiQ2AE=/?moveToWidget=3458764559655427655&cot=14

![Image](https://github.com/vegaprotocol/vegawallet-browser/assets/46783148/4f77b44f-b56f-4ef3-aed5-138b586ce50a)

## Design

[Figma link ↳ ](https://www.figma.com/file/rFlT1Ip2ot7Zfr2E5Is3Pd/Browser-Wallet?type=design&node-id=3988%3A2069&mode=design&t=ZUCHZAHo3QZkSEvT-1)

<img width="1975" alt="Assets-Per-Key-Per-Wallet" src="https://github.com/vegaprotocol/vegawallet-browser/assets/113684458/45ff84f5-582c-4b3d-8ee1-6cb3b7efbb73">

**Comment by JonRay15** [comment]
This is above the referral line
