### ISSUE TITLE
Transaction receipt 2nd pass: Transfers

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-browser#415]
## Story

**As a** user who placed an transfer
**I want** to see all the key details of my transfer transaction in my browser wallet
**So that** I can be certain I am approving the correct transaction

## Acceptance Criteria

- [ ] I can see a human readable 'receipt style' view of the key details when I am requested to approve / reject a Submit Order transaction
- [ ] The view contains the necessary data enrichment to provide
  - [ ] Size (with correctly formatted position decimals)
  - [ ] From Key
  - [ ] To Key
  - [ ] Indication of whether the transfers is between your own keys or an external one

## Tasks

- [x] Detailed sketch
- [x] Visual design
- [ ] Frontend tasks:
    - [ ] Implement UI
    - [ ] Integrate with backend
    - [ ] Write unit tests
- [ ] Backend tasks:
    - [ ] TBC
    - [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release

## Sketch

<img width="684" alt="image" src="https://github.com/vegaprotocol/vegawallet-browser/assets/89918817/55be8cd8-8d9b-4aab-8be7-bdd3a9b0cc86">

<img width="533" alt="image" src="https://github.com/vegaprotocol/vegawallet-browser/assets/89918817/aadaa32b-91d6-4a58-b4fe-1f63452fbeab">
