### ISSUE TITLE
Transaction receipt 2nd pass: Cancel order 

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-browser#418]
## Story

**As a** user who cancelled an order
**I want** to see all the key details of my order transaction and changes in my browser wallet
**So that** I can be certain I am approving the correct transaction

## Acceptance Criteria

- [ ] I can see a human readable 'receipt style' view of the key details when I am requested to approve / reject a Submit Order transaction
- [ ] The view contains the necessary data enrichment to provide
  - [ ] Market name
  - [ ] Direction
  - [ ] Size (with correctly formatted position decimals)
  - [ ] Price (with correctly formatted asset decimals)
    - [ ] Limit order handling
    - [ ] Market order handling
    - [ ] Pegged order handling
  - [ ] Time in force
  - [ ] Post / reduce only if applicable
- [ ] The view shows the order to be cancelled
- [ ] The view gives some indication that the order is being cancelled
- [ ] The view includes handling for:
  - [ ] Cancel single order by order ID
  - [ ] Cancel all orders on a market by market ID
  - [ ] Cancel all orders for a party by submitting nothing

## Tasks

- [x] Detailed sketch
- [x] Visual design
- [ ] Frontend tasks:
    - [ ] Implement UI
    - [ ] Integrate with backend
    - [ ] Write unit tests
- [ ] Backend tasks:
    - [ ] TBC
    - [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release

## Sketch

<img width="271" alt="image" src="https://github.com/vegaprotocol/vegawallet-browser/assets/89918817/ab778005-f1e0-42ef-b082-cdee43c71a6e">

I think the bin icon or striking through everything like this would be a good addition to the Figma sketches on this

<img width="481" alt="image" src="https://github.com/vegaprotocol/vegawallet-browser/assets/89918817/e644ffbf-559e-4431-9492-8f759c45ba60">

"Cancel All" 

<img width="390" alt="image" src="https://github.com/vegaprotocol/vegawallet-browser/assets/89918817/6d8be15c-6c6f-42f0-b678-f86441ec4503">

**Comment by JonRay15** [comment]
Superseded by new master ticket

**Comment by JonRay15** [comment]
We should confirm with Core if a cancel order that doesnt specify an order OR a market will cancel every single order that party has open.  We think no ... but confirm.

**Comment by JonRay15** [comment]
Confirmed with @jeremyletang 

yvon_or_justin
  [< 1 minute ago](https://vegaprotocol.slack.com/archives/C9E6XA8GK/p1695027295445979?thread_ts=1695027205.422199&cid=C9E6XA8GK)

3 possible cases:
- order + market ID -> cancel a specific order
- market ID -> cancel all orders in a market
- nothing -> cancel all orders, in all markets for the party.
