### ISSUE TITLE
Transaction receipt 2nd pass: Order amendment

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-browser#419]
## Story

**As a** user who amended an order
**I want** to see all the key details of my order transaction and changes in my browser wallet
**So that** I can be certain I am approving the correct transaction

## Acceptance Criteria

- [ ] I can see a human readable 'receipt style' view of the key details when I am requested to approve / reject a Submit Order transaction
- [ ] The view contains the necessary data enrichment to provide
  - [ ] Market name
  - [ ] Direction
  - [ ] Size (with correctly formatted position decimals)
  - [ ] Price (with correctly formatted asset decimals)
    - [ ] Limit order handling
    - [ ] Market order handling
    - [ ] Pegged order handling
  - [ ] Time in force
  - [ ] Post / reduce only if applicable
  - [ ] The view shows the old / new values with strikethroughs

## Tasks

- [x] Detailed sketch
- [x] Visual design
- [ ] Frontend tasks:
    - [ ] Implement UI
    - [ ] Integrate with backend
    - [ ] Write unit tests
- [ ] Backend tasks:
    - [ ] TBC
    - [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release

## Sketch

<img width="558" alt="image" src="https://github.com/vegaprotocol/vegawallet-browser/assets/89918817/f137dde4-88b3-455b-be06-0c9cadea03cb">

**Comment by JonRay15** [comment]
Replacing this with a single ticket for all second passes.
