### ISSUE TITLE
Cancel Stop Order Receipt View

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-browser#420]
## Story

**As a** user who cancelled a Stop Order
**I want** to see all the key details of my order transaction in my browser wallet
**So that** I can be certain I am approving the correct transaction

## Acceptance Criteria

- [ ] I can see a human readable 'receipt style' view of the key details when I am requested to approve / reject a Cancel Stop Order transaction
- [ ] II can see a human readable 'receipt style' view of Cancel Stop Order transactions I have already approved/rejected in the transactions list in my wallet

## Tasks

- [ ] Detailed sketch
- [ ] Visual design
- [ ] Frontend tasks:
    - [ ] Implement UI
    - [ ] Integrate with backend
    - [ ] Write unit tests
- [ ] Backend tasks:
    - [ ] TBC
    - [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release

## Sketch
Follow patterns established by #418
