### ISSUE TITLE
Warn user when unable to get transaction data

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-browser#425]
## Story

**As a** browser wallet user
**I want** to know when the wallet hasn't been able to load transaction data
**So that** I understand what's happening and the risk of my transaction failing

Some of the scenarios this might include:

- In the case of loss of internet connection?
- Data node connected to stops working?
- Rate limiting means that the data node doesn't respond - might need core support for this (desktop wallet uses GRPC where as we have to use Rest and this is rate limited)

We've been unable to load the data for this transaction proceed at your own risk, it might fail. :-) 

## Acceptance Criteria

- [ ] I am informed that the wallet has been unable to load the data for my transaction
- [ ] I am given information about why (if/when we are able to determine a reason OR something generic about the sorts of things that might cause it)
- [ ] I am informed of what this might mean i.e. the transaction might fail and any action I might be able to take to resolve the issue

## Tasks

- [ ] Detailed sketch
- [ ] Visual design
- [ ] Frontend tasks:
    - [ ] Implement UI
    - [ ] Integrate with backend
    - [ ] Write unit tests
- [ ] Backend tasks:
    - [ ] TBC
    - [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release
