### ISSUE TITLE
Use generic transaction view for Iceberg, LP and Pegged Orders

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-browser#426]
## Chore

We have deprioritised Transaction Receipt Views for Iceberg, LP and Pegged Orders because we believe that fish and shrimp are not likely to use these transaction types, so we will add support for these later on when adding features for a wider audience and power users. 

In the interim, we want to detect when a transaction is for an Iceberg, LP or Pegged Order (Submit, Amend and Cancel variations) and fall back to the generic json transaction view for those.

## Tasks

- [ ] Frontend tasks:
    - [ ] Implement UI
    - [ ] Integrate with backend
    - [ ] Write unit tests
- [ ] Backend tasks:
    - [ ] TBC
    - [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release

**Comment by dexturr** [comment]
This is free
