### ISSUE TITLE
Prompt to deposit

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-browser#427]
## Story

**As a** browser wallet user
**I want** to be prompted to deposit assets if I don't already have some deposited 
**So that** I know what I need to do to get trading as quickly as possible 

## Acceptance Criteria

- [ ] I am shown a message prompting me to deposit assets if I don't currently have any 
- [ ] I am not shown a message prompting me to deposit assets if I do already have assets (instead I am [shown my asset balance](https://github.com/vegaprotocol/vegawallet-browser/issues/408))

## Tasks

- [ ] Detailed sketch
- [ ] Visual design
- [ ] Frontend tasks:
    - [ ] Implement UI
    - [ ] Integrate with backend
    - [ ] Write unit tests
- [ ] Backend tasks:
    - [ ] TBC
    - [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release

## Sketch
<img width="460" alt="Screenshot 2023-07-21 at 18 13 37" src="https://github.com/vegaprotocol/vegawallet-browser/assets/47143694/ce924283-5f60-4d90-8c3e-b78e18651725">

**Comment by JonRay15** [comment]
This is done
