### ISSUE TITLE
CTA to withdraw funds

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-browser#428]
## Story

**As a** browser wallet user
**I want** to see a way to withdraw funds from the browser wallet
**So that** I understand that I can, and to be able to initiate the process from the wallet

## Acceptance Criteria

- [ ] I can see a way to withdraw which takes me to console withdraw screen
- [ ] I can see a link to deposit which takes me to console deposit screen
- [ ] I can see a link to transfer which takes me to console transfer screen
- [ ] The link to "Browse" is removed cos that is pointless
- [ ] When I click to initiate a withdrawal I am taken directly to the withdraw modal in Console (TBD what Console might need to do about it!)

## Tasks

- [ ] Design
- [ ] Build
- [ ] Test

## Sketch

https://miro.com/app/board/uXjVPUiQ2AE=/?moveToWidget=3458764560400939920&cot=14
![Image](https://github.com/vegaprotocol/vegawallet-browser/assets/46783148/9fa20651-c9a4-478c-8b0d-afe6499c6e12)

**Comment by JonRay15** [comment]
Note that in Console lan d they have 

Two tickets (monorepo 4647 and 4648) which along with a previous ticket I dont know have now created dedicated pages for deposit, withdraw, and transfers ... we are hoping we can get those out to mainnet in the next few days, and if so we could link them up here.  So lets make sure we sync up on that.
