### ISSUE TITLE
Make mainnet the default network for the browser wallet

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-browser#431]
Should be timed with incentive feedback so we do this after any critical bugs are found / fixed.

## Chore

We need to update configuration etc. so ensure that mainnet is the default network for the primary browser release, that is published to the webstores

## Tasks

- [ ] Detailed sketch
- [ ] Visual design
- [ ] Frontend tasks:
    - [ ] Implement UI
    - [ ] Integrate with backend
    - [ ] Write unit tests
- [ ] Backend tasks:
    - [ ] TBC
    - [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release

**Comment by ckpringle** [comment]
Duplicate of #430
