### ISSUE TITLE
Sign message - stretch

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#437]
## Story

**As a** user
**I want** a way to sign a message with a key
**So that** I can prove my ownership of that key to earn incentives

## Acceptance Criteria

- [ ] There is a way to type a message from a key 
- [ ] There is a way to "sign" the message from the key, creating a verifiable link
- [ ] I can copy the signed message to clipboard

## Tasks

- [ ] Sketch UI 
- [ ] Frontend tasks:
    - [ ] Implement UI
    - [ ] Integrate with backend
    - [ ] Write unit tests
- [ ] Backend tasks:
    - [ ] Integrate with sign message API
    - [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release

## Sketch
From Desktop Wallet:
<img width="380" alt="Screenshot 2023-07-25 at 09 21 08" src="https://github.com/vegaprotocol/vegawallet-browser/assets/46783148/77f00fc9-b85a-4c9d-8867-8e2ba566d4db">
<img width="378" alt="Screenshot 2023-07-25 at 09 21 24" src="https://github.com/vegaprotocol/vegawallet-browser/assets/46783148/e72f58e1-bc7e-454f-a418-63641f9e9173">

## Notes

- This exists on desktop wallet on click of a specific key
- We'd need a different interaction (for now) while the view is wallet centred, e.g. a menu / action from each key in a list?

**Comment by ckpringle** [comment]
Existing users could sign a message using the desktop wallet and then import that key in to browser wallet.
