### ISSUE TITLE
Easy to read transaction for applying a referral code / joining a team

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#451]
We wrote this while the transactions were still being agreed with Core - relates to #444 

## Chore

This is what we currently have

![Image](https://github.com/vegaprotocol/vegawallet-browser/assets/89918817/3a6ace58-374d-412c-aee0-8d08b8f8e54d)

Can we make this slightly nicer?

## Tasks

- [ ] Decide what we need 
- [ ] Build it
- [ ] TEst it

## Acceptance Criteria

- [ ] I can see the code I'm joining nicely formatted
- [ ] Thats it ... the rest is on the referral site
