### ISSUE TITLE
Share new keys with connected dApps

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#453]
## Chore

When a user adds a key to their wallet, we need to "tell" dapps about it so that they can reflect the new key in their UIs.

## Tasks

- [ ] There is a way tell the dapp someone has added keys because someone has added keys
- [ ] If Console is open and connected and then someone creates a new key on the wallet, Console should reflect that immediately and not need a refresh
- [ ] The event should be app agnostic, it shoudl work for console and any other dapp that wants to connect.

**Comment by JonRay15** [comment]
I think this is already done?  When I create a new key in the wallet and I'm connected to Console it is displayed immediately ... I dont have to refresh or anything?
