### ISSUE TITLE
Update key pair / rename

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#454]
## Story

**As a** user
**I want** to rename my key 
**So that** I can organise my keys in the way that suits my mental model of how I use the keys

## Acceptance Criteria

- [ ] There is a way to rename a key 
- [ ] I can see the new name in the wallet UI
- [ ] The new name of a key is shared with connected dapps (backend)

## Tasks

- [ ] Detailed sketch
- [ ] Visual design
- [ ] Frontend tasks:
    - [ ] Implement UI
    - [ ] Integrate with backend
    - [ ] Write unit tests
- [ ] Backend tasks:
    - [ ] TBC
    - [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release

## Sketch

![Image](https://github.com/vegaprotocol/vegawallet-browser/assets/46783148/f3afd614-e264-4b57-8cc8-1f3e131f179b)

## Notes
Rename after you've used Vega... not onboarding

![Image](https://github.com/vegaprotocol/vegawallet-browser/assets/46783148/6d870c9d-f653-49a4-9519-a41c09f5c92b)

**Comment by JonRay15** [comment]
BEOLW THE LINE

**Comment by JonRay15** [comment]
Back ABOVE THE LINE now we have Sam
