### ISSUE TITLE
Update browser wallet to support perpetual markets

### ISSUE THREAD

**Issue by neildawson** [vegaprotocol/vegawallet-browser#460]
## The Chore

The browser wallet must be updated to support perpetual markets

## Tasks

- [x] Update to support the addition of new perpetual market fields
- [x] Update the protos
- [x] Ensure we can approve a new market proposal 
- [x] Ensure we can approve a market update proposal
- [ ] ~Ensure we can support orders on perps~
- [ ] ~Ensure we can support order amendments on perps~
- [ ] ~Ensure we can support cancels on perps~
- [ ] ~Any required changes to receipt views~
- [x] Dale to look at whether automation covers this

**Comment by JonRay15** [comment]
Done
