### ISSUE TITLE
Send disconnect event to dapp when disconnecting via 'list connections' page in wallet

### ISSUE THREAD

**Issue by dalebennett1992** [vegaprotocol/vegawallet-browser#467]
## Story

**The below story already exsists in the spec repo, we should append the AC to it**

As a wallet user 
I want to be able to disconnect a dapp connection from my wallet (revoking access to my keys)
So that I can be in control of who/what has access to my keys 

## Acceptance Criteria

- [ ] The dapp is informed of the disconnection via an event handler
- [ ] Console needs to respond to that disconnect by no longer showing you as connected
- [ ] This needs to work even if multiple tabs are open with multiple connections
  - [ ] If two tabs of console are open they should be displayed as two connections in the wallet
  - [ ] If you disconnect one of the two connections only that relevant one should be disconnected

## Tasks

- [ ] Backend tasks:
    - [ ] send disconnect event
    - [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release

**Comment by JonRay15** [comment]
Can we get this picked up when @emilbayes is back?

Its one of our objectives for this sprint to get teh UX smoothed around disconnects / keep alive etc.

**Comment by JonRay15** [comment]
3 cases where disconnects occur:

1. You lock your wallet
    2. Console could completely disconnect you in this case immediately
    3. Or Console could remain connected and let you browse, but if you sent a TX the wallet would require you to unlock to sign the TX
4. You remove the app from your approved connections list
    5. In this case it seems clear that you should disconnect Console immediately
    6. But we need to know what automatic reconnect logic Console has because if it kept trying to immediately reconnect that would be annoying
 7. When the extension goes to sleep (which the keep-alive should mitigate) or your entire computer goes to sleep (which keep -alive does not mitigate)... at this point the disconnect event would be sent once it wakes up 
    8.  We could expect Console to immediately try to reconnect in this case because you didnt explicitly disconnect
    9. Or we could just make the disconnect and the user would need to explicitly reconnect at this point

Need to get to answers on these to proceed.

**Comment by JonRay15** [comment]
1. You lock your wallet 
  a. No disconnect event, any transactions should queue up in the wallet 
  b. You would need to unlock your wallet to proceed with these
2. You revoke the permissions
  a. After this occurs the changes to / new set of approved keys needs to get to the dApp
  b. The dApp needs to respond to that appropriately
3.

**Comment by JonRay15** [comment]
The PR currently linked to this (466) is now redundant ... so @emilbayes will be putting up another one soon and linking to this.
