### ISSUE TITLE
First pass of all priority transaction receipts

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vegawallet-browser#481]
## Story

As a user
I want to see the basic view of transactions for all types
So that I can review my Txs

## Acceptance Criteria

- [ ] I can see the basic info for all priority types (below)
- [ ] I can NOT yet see nicely formatted price etc 

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

## Additional details / background info

Transaction types supported:
- Order submission
- Order amendement
- Order cancellation
- Transfer
- Withdrawal
- Batch market instructions
- Stop order submission
- Stop order cancellation

So types NOT supported:
- Amend liquidity provision order
- Cancel liquidity provision order
- Cancel transfer funds
- Create liquidity provider order
- Delegate
- Proposal
- Submit oracle data
- Undelegate
- Vote on proposal
- Chain event
- Ethereum key rotation submission
- Issue signatures
- Key rotate submission
- Node signature
- Node vote
- Protocol upgrade
- Register new node
- State variabel proposal
- Validator heartbeat

**Comment by dexturr** [comment]
Still needs:

* Stop order submission
* Add price components to existing views (where possible)
* Batch market instructions

**Comment by JonRay15** [comment]
Need some Dale eyes on stop orders, pegged orders, and batch markets. 

And do a final sweep.
