### ISSUE TITLE
Handle multiple requests via popouts

### ISSUE THREAD

**Issue by dalebennett1992** [vegaprotocol/vegawallet-browser#483]
## Story

As a user of browser wallet I want the popout to remain open if there are still requests to action, so that I can handle all notifications in one place

## Acceptance Criteria

- [ ] If I queue more than one connection requests the popout appears and remains open until I have addressed all connection requests
- [ ] If I queue more than one transaction request the popout appears and remains open until I have addressed all transactions

## Tasks

- [ ] Detailed sketch
- [ ] Visual design
- [ ] Frontend tasks:
    - [ ] Implement UI
    - [ ] Integrate with backend
    - [ ] Write unit tests
- [ ] Backend tasks:
    - [ ] TBC
    - [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release

**Comment by JonRay15** [comment]
Decided this was too painful for the value it delivered. Descoped.
