### ISSUE TITLE
Handle data loading in receipt views

### ISSUE THREAD

**Issue by dalebennett1992** [vegaprotocol/vegawallet-browser#484]
## Story

Remaining AC for 1114-RCPT

## Acceptance Criteria

- [ ] I see a loading state while the enrichment data is loading
- [ ] If there is an error loading the data I see an indication of it

## Tasks

- [ ] Detailed sketch
- [ ] Visual design
- [ ] Frontend tasks:
    - [ ] Implement UI
    - [ ] Integrate with backend
    - [ ] Write unit tests
- [ ] Backend tasks:
    - [ ] TBC
    - [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release
