### ISSUE TITLE
Increase speed of the Console network check

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vegawallet-browser#486]
## The Chore

When console (or governance app) checks with the wallet to find out the network currently it whirs around for quite a long time.  This is because Console sends a request to the wallet to ask what chain ID it is on, then the wallet sends requests to datanodes to ask this.  If a few datanodes are needed it takes a while. 

This shouldnt be taking this long because the wallet should already know which chain it is on when it boots up.  Therefore it should be able to respond instantly.

## Tasks

- [ ] Make sure the browser wallet is caching the chain ID its on when it starts up 
- [ ] Make sure it can provide this to Console instantly
- [ ] Confirm in tests that Console is now fast

**Comment by JonRay15** [comment]
The web wallet check on datanodes is different already.

Once it has contacted the first datanode the others only have a short amount of time (we think 800ms) before it will just go with the first one rather than continue the round robin. 

So we dont see this behaviour on web wallet, it is generally doing this in <2s. 

So I'm closing this and will keep an eye on it.
