### ISSUE TITLE
Allow user to delete / remove a wallet

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/vegawallet-browser#501]
## Story

**As a user
**I want to be able to delete my wallet
**So that I can import a new one

## Linked tasks

* #542 
* #543 

## Acceptance Criteria

- [ ] I can delete my wallet with some option deep in the settings
- [ ] I am ask to confirm my choice
- [ ] I am reminded that i need to export my recovery phrase if havent already
- [ ] I can see an explanation that once done I will need to re-import my wallet by recovery phrase if I want it back

## Tasks

- [ ] Detailed sketch
- [ ] Visual design
- [ ] Frontend tasks:
    - [ ] Implement UI
    - [ ] Integrate with backend
    - [ ] Write unit tests
- [ ] Backend tasks:
    - [ ] TBC
    - [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release

**Comment by barnabee** [comment]
Delete seems like the wrong word, perhaps "remove" instead?

**Comment by dexturr** [comment]
@barnabee Remove feels a bit too soft to me, if you're removing a mnemonic we need it to be obvious that the user needs to have stored thier mnemonic to add the wallet again in future (until multi wallet). Perhaps solvable with a dialog explaining all of this.

**Comment by barnabee** [comment]
@dexturr I'd rather be "too soft" than wrong, given that a wallet cannot be deleted.

I think as you suggest the answer here is that the confirmation dialog when removing a wallet states that once it is removed the wallet cannot be recovered/re-added without the seed phrase.

Relatedly, we should also make sure to prioritise these issues that enable a use to see their secret seed phrase and private keys:

* #542 
* #543
