### ISSUE TITLE
Update console links

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/vegawallet-browser#519]
## Story

**As a** user
**I want** the calls to action to take me to the screens they relate to
**So that** I can perform that action more easily

## Acceptance Criteria

- [ ] I can go to console with the deposit view selected
- [ ] I can go to console with the transfer view selected
- [ ] I can go to console with the withdraw view selected

## Tasks

- [ ] Detailed sketch
- [ ] Visual design
- [ ] Frontend tasks:
    - [ ] Implement UI
    - [ ] Integrate with backend
    - [ ] Write unit tests
- [ ] Backend tasks:
    - [ ] TBC
    - [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release
