### ISSUE TITLE
Transaction receipt 2nd pass: Submit Order

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vegawallet-browser#524]
## Story

**As a** user who placed an Order
**I want** to see all the key details of my order transaction in my browser wallet
**So that** I can be certain I am approving the correct transaction

## Acceptance Criteria

- [x] I can see a human readable 'receipt style' view of the key details when I am requested to approve / reject a Submit Order transaction
- [ ] The view contains the necessary data enrichment to provide
  - [ ] Market name
  - [ ] Size (with correctly formatted position decimals)
  - [ ] Price (with correctly formatted asset decimals)
    - [ ] Limit order handling
    - [ ] Market order handling

## Tasks

- [x] Detailed sketch
- [x] Visual design
- [ ] Frontend tasks:
    - [ ] Implement UI
    - [ ] Integrate with backend
    - [ ] Write unit tests
- [ ] Backend tasks:
    - [ ] TBC
    - [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release

## Sketch

<img width="256" alt="image" src="https://github.com/vegaprotocol/vegawallet-browser/assets/89918817/32b7c5db-1135-4b86-9527-d579ff84c18d">

<img width="1189" alt="image" src="https://github.com/vegaprotocol/vegawallet-browser/assets/89918817/454b2425-fbbe-4110-a488-c0d875601faf">
