### ISSUE TITLE
Transaction receipt 2nd pass: Batch intructions

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vegawallet-browser#526]
## Story

**As a** user who placed a batch instuction
**I want** to see all the key details of my order transaction and changes in my browser wallet
**So that** I can be certain I am approving the correct transaction

## Acceptance Criteria

- [ ] I can see a human readable 'receipt style' view of the key details when I am requested to approve / reject a Submit Order transaction
- [ ] The view contains the necessary data enrichment to provide
  - [ ] Market name
  - [ ] Direction
  - [ ] Size (with correctly formatted position decimals)
  - [ ] Price (with correctly formatted asset decimals)
    - [ ] Limit order handling
    - [ ] Market order handling
    - [ ] Pegged order handling
  - [ ] Time in force
  - [ ] Post / reduce only if applicable
  - [ ] Trigger price 
  - [ ] Trigger direction
  - [ ] Expiry
  - [ ] OCO if applicable

NB. I dont really know WHAT is needed  here .... never seen a batch order .... presumably they can contain any combination of other orders and therefore might need to show all the various things that are shown in each individual type ... or maybe we just show order IDs ... dont know ..... the nature of this therefore might change depending on what was implemented in the first pass.  But basically if we implemented anything in the first pass that we'd be better off enriching ...then we should do that!

## Tasks

- [x] Detailed sketch
- [x] Visual design
- [ ] Frontend tasks:
    - [ ] Implement UI
    - [ ] Integrate with backend
    - [ ] Write unit tests
- [ ] Backend tasks:
    - [ ] TBC
    - [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release
