### ISSUE TITLE
Allow user to reveal their seed phrase

### ISSUE THREAD

**Issue by barnabee** [vegaprotocol/vegawallet-browser#542]
## Story

**As a user**
**I want to be able to retrieve my seed phrase after creating a wallet**
**So that I can easily import my wallet elsewhere or recover the phrase if I've lost access to other backups**

## Acceptance Criteria

- [x] I can click a button/menu item to recover the seed phrase for any of my wallet stored in Vega Wallet for Browsers
- [x] I must enter my password before the seed phrase is shown to me
- [x] I can click to copy the seed phrase

## Tasks

- [ ] Detailed sketch
- [ ] Visual design
- [ ] Frontend tasks:
    - [ ] Implement UI
    - [ ] Integrate with backend
    - [ ] Write unit tests
- [ ] Backend tasks:
    - [ ] TBC
    - [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release

**Comment by JonRay15** [comment]
We can export the private key now ... do we also need the seed phrase?
