### ISSUE TITLE
Allow user to retrieve private key for a specific key pair

### ISSUE THREAD

**Issue by barnabee** [vegaprotocol/vegawallet-browser#543]
## Story

**As a user**
**I want to be able to retrieve the private key for a specific keypair within my wallet**
**So that I can use individual keys in other wallet systems or applications without sharing my full seed phrase, and use keys from my wallet in systems that don't support BIP39 key generation.**

## Acceptance Criteria

- [ ] I can select a wallet and key and choose an option to reveal the private key 
- [ ] I must enter my password before being shown the key
- [ ] I can click to copy the private key
- [ ] I am warned not to share this key with anyone etc.

## Tasks

- [ ] Detailed sketch
- [ ] Visual design
- [ ] Frontend tasks:
    - [ ] Implement UI
    - [ ] Integrate with backend
    - [ ] Write unit tests
- [ ] Backend tasks:
    - [ ] TBC
    - [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release

## Notes
<img width="374" alt="Screenshot 2023-09-24 at 16 30 50" src="https://github.com/vegaprotocol/vegawallet-browser/assets/1179257/71c6fbb6-2e19-424e-81b6-1447472b02b0">
<img width="369" alt="Screenshot 2023-09-24 at 16 30 56" src="https://github.com/vegaprotocol/vegawallet-browser/assets/1179257/44e15bbe-9075-44c9-8a7b-425c99883b75">
<img width="369" alt="Screenshot 2023-09-24 at 16 31 02" src="https://github.com/vegaprotocol/vegawallet-browser/assets/1179257/3ff00f4c-2606-4dc2-97f6-03024f4557d6">
<img width="365" alt="Screenshot 2023-09-24 at 16 31 41" src="https://github.com/vegaprotocol/vegawallet-browser/assets/1179257/9b15088f-1443-4d47-a45e-238b30a1ef03">
