### ISSUE TITLE
Back button on create wallet page

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/vegawallet-browser#550]
## Story

**As a** user
**I want** top be able to go back from create wallet
**So that** I can import a wallet instead

## Acceptance Criteria

- [ ] I can go back from the create a wallet page

## Tasks

- [ ] Detailed sketch
- [ ] Visual design
- [ ] Frontend tasks:
    - [ ] Implement UI
    - [ ] Integrate with backend
    - [ ] Write unit tests
- [ ] Backend tasks:
    - [ ] TBC
    - [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release
