### ISSUE TITLE
View assets per key additional functionality

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/vegawallet-browser#562]
## Story

Fix now:

**As a** user
**I want** to see an error state
**So that** I am informed why the view is not working

As a user
I want to see a reasonable empty state
So that I am informed about how to deposit assets to vega and which markets I can trade in

**As a** user
**I want** the market lozenges in the expanded view
**So that** the view is not so busy

Split to other tickets

#576 
#577 

## Acceptance Criteria

Split out into other tickets:

Unit test:
- [ ] Some version of this expanded view is shown when hovering over the asset too
- [ ] Once expanded there are buttons / icons prompting me to deposit / withdraw / transfer that asset which take me to the relevant screen in console - probably initially the side bar but eventually the guided flow, and ideally with the asset already set in each case assuming Console can support this in time. Relies on #502 which relies on console deploying to mainnet.
- [ ] If I have no funds, by default USDT and VEGA are displayed with the same expansion behaviour and the CTAs to deposit displayed therein
- [ ] The list of assets is sorted in descending order of balance held (in quantum terms) 

E2e:
- [ ] I can see the markets each is currently traded in, up to a max of 5 sorted by top volume 

## Tasks

- [ ] Detailed sketch
- [ ] Visual design
- [ ] Frontend tasks:
    - [ ] Implement UI
    - [ ] Integrate with backend
    - [ ] Write unit tests
- [ ] Backend tasks:
    - [ ] TBC
    - [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release

**Comment by dexturr** [comment]
> As a user
I want the list sorted by my most valuable assets (quantum) to least
So that I can easily find which assets I have the most of

This is going to be really annoying and difficult. I suggest descoping, the only way to get 24hr volume is to request the candles for each market which leads into an N+1 that I'd rather avoid. Instead I suggest we just pick the top 5 as given to us by core.
