### ISSUE TITLE
Improve caching of data loaded to enrich transaction views

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vegawallet-browser#586]
## Chore

Improve caching to help performance on receipts

Currently there is a second of delay before the key view is displayed when you load the wallet.  Need to improve this and improve the sequencing of it.

## Tasks

- [x] Implement caching on assets
- [x] Implement caching on markets
- [x] Improve the sequencing on the front end because at the moment the delay is visible on load even though the info on that first page doesnt actually require that data
