### ISSUE TITLE
Size should be in quoteAsset

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/vegawallet-browser#601]
## Story

**As a** user
**I want** to see the units of contract size
**So that** I can tell what the size units are

## Acceptance Criteria

- [ ] I can see the size units `quoteAsset` of the market the order is being placed on

## Tasks

- [ ] Detailed sketch
- [ ] Visual design
- [ ] Frontend tasks:
    - [ ] Implement UI
    - [ ] Integrate with backend
    - [ ] Write unit tests
- [ ] Backend tasks:
    - [ ] TBC
    - [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release

**Comment by JonRay15** [comment]
We established this was wrong and had to roll it back in Console. Closing
