### ISSUE TITLE
EPIC: Multi-network support

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vegawallet-browser#609]
## Story

**As a**
**I want**
**So that**

## Quetsions

- Are we running a single wallet which adapts to fairgroung vs mainnet 
- How to handle network switching
- How to handle network import
- If we want to handle dynamic network switching we need Console / Governance to say what chain ID they're on so the wallet can respond to it
- How to handle balances without the concept of a selected network?
  - Could Console tell you?
  - What if you're not connected to anything?
  - Or could we have a selected network in the app, BUT inbound transactions can bypass this (maybe with a warning)

## Acceptance Criteria

- [ ] There is a "canary" and "main" version of the wallet
- [ ] One wallet will cover all lower enviroments (testnet, stagnet, and validator testnet)
- [ ] We will generally keep up with stagnet releases if we determine they impact us, with backward compatibility to testnet assumed
- [ ] The other wallet will cover mainnet and mainnet mirror, which will always be on the same code
- [ ] 

## Tasks

- [ ] Detailed sketch
- [ ] Visual design
- [ ] Frontend tasks:
    - [ ] Implement UI
    - [ ] Integrate with backend
    - [ ] Write unit tests
- [ ] Backend tasks:
    - [ ] TBC
    - [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release

**Comment by dexturr** [comment]
Frontend notes:

* Connection needs to be specific to network and must display that network 
* Sending a transaction must show the network it will be placed on
* Need concept of a "selected network" for frontend only for displaying data on pages
* Show which connections are connected on which networks

**Comment by JonRay15** [comment]
This is all complete
