### ISSUE TITLE
EPIC: Restore to factory state

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vegawallet-browser#615]
## Story

**As a** user
**I want** the ability to reset my wallet app
**So that** I can import a different wallet or create a new one without having to open a new browser

## Acceptance Criteria

- [ ] I can reset my wallet app
- [ ] I can trigger this reset from withing the settings somewhere
- [ ] I can now create / import a wallet as usual

## Tasks

- [ ] Detailed sketch
- [ ] Visual design
- [ ] Frontend tasks:
    - [ ] Implement UI
    - [ ] Integrate with backend
    - [ ] Write unit tests
- [ ] Backend tasks:
    - [ ] TBC
    - [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release
