### ISSUE TITLE
feat: sort lozenges and empty state by open interest

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/vegawallet-browser#619]
## Story

**As a** user
**I want** to see a reasonable empty state
**So that** I am informed about how to deposit assets to vega and which markets I can trade in

**As a** user
**I want** the markets shown to be the top 5 (that are in continuous trading or price monitoring auction) by volume
**So that** I can easily find markets to trade with my assets

Use openInterest converted to quantum to sort the list.

## Acceptance Criteria

- [ ] I can
- [ ] I can
- [ ] I can

## Tasks

- [ ] Detailed sketch
- [ ] Visual design
- [ ] Frontend tasks:
    - [ ] Implement UI
    - [ ] Integrate with backend
    - [ ] Write unit tests
- [ ] Backend tasks:
    - [ ] TBC
    - [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release

**Comment by JonRay15** [comment]
Not important until we have more markets
