### ISSUE TITLE
Handle the dApp providing bad data for ids

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/vegawallet-browser#625]
## Story

**As a** user
**I want** to be notified if we could not find an asset/market/order
**So that** I can make an informed choice about submitting my transaction

## Acceptance Criteria

- [ ] I can see a warning if the market/asset/order could not be found
- [ ] I can see a checkbox to proceed with my transaction
- [ ] I can submit the transaction if the checkbox is ticked

## Tasks

- [ ] Detailed sketch
- [ ] Visual design
- [ ] Frontend tasks:
    - [ ] Implement UI
    - [ ] Integrate with backend
    - [ ] Write unit tests
- [ ] Backend tasks:
    - [ ] TBC
    - [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release
