### ISSUE TITLE
Inform user when a closeout batch transaction is happening

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/vegawallet-browser#628]
## Story

**As a** user
**I want** to know that placing a reduce only transaction with a large size will only close my position
**So that** I don't think I will open a large position in the opposite direction

## Acceptance Criteria

- [ ] I can see the size field displaying something other than max unit64 
- [ ] I can see an explination about why this occurs
- [ ] I can see a link to the docs about how this works

## Tasks

- [ ] Detailed sketch
- [ ] Visual design
- [ ] Frontend tasks:
    - [ ] Implement UI
    - [ ] Integrate with backend
    - [ ] Write unit tests
- [ ] Backend tasks:
    - [ ] TBC
    - [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release

**Comment by dexturr** [comment]
No longer in scope
