### ISSUE TITLE
EPIC: Fix keep alive and general wallet / console "jankyness"

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vegawallet-browser#632]
## Chore

You get disconnected after like 5 mins

Make it stop.

### Browser Wallet Team

- [x] Send a proper disconnect even:  https://github.com/vegaprotocol/vegawallet-browser/issues/467 
- [x] Completed documentation: #653 
- [x] Fix the keep alive issue #654

### Console / Governance Teams

- [x] Deliver changes on Console and other apps to handle the case where a transaction is sent and the wallet is clearly disconnected (https://github.com/vegaprotocol/frontend-monorepo/issues/4717)
- [x] Deliver this ticket to respond to disconnect event https://github.com/vegaprotocol/frontend-monorepo/issues/5443

### Testing
- [ ] Add a test that waits 30s and then tries again as this will align to what Chrome is telling us

**Comment by JonRay15** [comment]
This is done
