### ISSUE TITLE
Detect a close position order and show in receipt

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vegawallet-browser#633]
## Chore

Background is on here 

https://github.com/vegaprotocol/frontend-monorepo/issues/5110

## Tasks

- [ ] On any order submission check for combination of reduce only + size of 9223372036854775807
- [ ] If detected instead of displaying the  number display "MAX" for the size
- [ ] Display "Close Position" somewhere on the receipt view
- [ ] On hover show the full number

## Notes

Cancellations
- Mass Order Cancellation (if !orderId)
- Cancellation (else)
...
Submissions
- Order submission
- Close position (if reduceOnly && size === max)
