### ISSUE TITLE
Improve transaction status feedback from wallet 

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-browser#64]
## Story

As a user 
I want to see what node the transaction was sent to and track it's progress (success/failure) when submitting transactions via the desktop wallet 
So that I can understand the status 

## Recording 

https://user-images.githubusercontent.com/46783148/214906347-9f31385e-af3b-40dd-8d21-28df6fd03e99.mov

## Tasks

- [ ] Identify transaction types and feedback available (conversation with Botond, Valentine?) 
- [ ] Work out the ideal flow from / in wallet and/or to block explorer...
- [ ] Team and stakeholder review
- [ ] Visual Design
- [ ] Team review
- [ ] Etc.

## Acceptance Criteria

- [ ] I can
- [ ] I can
- [ ] I can

**Comment by pennyandrews** [comment]
seems I already identified this as not in the right repo but failed to actually close it. Doing so now
