### ISSUE TITLE
EPIC: Transaction lists & queues

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vegawallet-browser#665]
## Story

**As a** user
**I want** to be able to see the full list of transactions I've approved historically, plus the current queue
**So that** I know exactly what my wallet has done and is doing.

## Linked Tasks

#143 
#144 
#185 
#85 
#483 
#510 

## Acceptance Criteria

- [ ] I can
- [ ] I can
- [ ] I can

## Tasks

- [ ] Detailed sketch
- [ ] Visual design
- [ ] Frontend tasks:
    - [ ] Implement UI
    - [ ] Integrate with backend
    - [ ] Write unit tests
- [ ] Backend tasks:
    - [ ] TBC
    - [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release
