### ISSUE TITLE
EPIC: Interim mainnet / fairground wallet solution in lieu of full multi-network

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vegawallet-browser#668]
## Story

**As a** user that has just competed in a game of fairground and won rewards
**I want** a smoother UX when getting the mainnet wallet which plays more nicely with the fairground wallet
**So that** I can survive until we have proper multi-network

## Acceptance Criteria

- [ ] I can
- [ ] I can
- [ ] I can

## Tasks

- [ ] Confirm with console a migration plan
- [ ] Merge emils PR
- [ ] Get connection flow working with new APIs
- [ ] Get links working with new config model
- [ ] Add tests for multi-network
- [ ] Network switcher
- [ ] Add network details to settings
- [ ] Add connection details page so you can see which network a dapp has access to
- [ ] Fix disclaimer
- [ ] Adjust fetch API for selected network
- [ ] Remove double build from CI
