### ISSUE TITLE
EPIC: Import wallet created using the metamask snap

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vegawallet-browser#669]
## Story

**As a** user who has generated a wallet using the snap
**I want** to be able to import that wallet into Browser Wallet
**So that** I dont have to lose my wallet or move funds between keys

## Acceptance Criteria

- [x] #691 
- [x] #708 

## Tasks

- [ ] Detailed sketch
- [ ] Visual design
- [ ] Frontend tasks:
    - [ ] Implement UI
    - [ ] Integrate with backend
    - [ ] Write unit tests
- [ ] Backend tasks:
    - [ ] TBC
    - [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release

**Comment by JonRay15** [comment]
This is all done
