### ISSUE TITLE
Add wallet locking

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vegawallet-browser#676]
## Story

**As a** user
**I want** my wallet to have a lock mode, which can be triggered manually and automatically
**So that** I am protected from leaving my laptop open

## Acceptance Criteria

- [ ] There is a button somewhere to lock my wallet manually (see Metamask screenshot)
- [ ] There is an automatic lock feature that will lock the wallet after a period of inactivity
- [ ] There is a setting to specify the duration of that timeout (including setting to "never")

## Tasks

- [ ] Detailed sketch
- [ ] Visual design
- [ ] Frontend tasks:
    - [ ] Implement UI
    - [ ] Integrate with backend
    - [ ] Write unit tests
- [ ] Backend tasks:
    - [ ] TBC
    - [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Team verify acceptance criteria met
- [ ] Exploratory QA testing 
- [ ] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders
- [ ] Release

## Sketch

<img width="227" alt="image" src="https://github.com/vegaprotocol/vegawallet-browser/assets/89918817/e122a6d6-cdeb-48fe-b0a3-3af2affc2879">
