### ISSUE TITLE
Implement Client: Send transaction api endpoint

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vegawallet-browser#68]
## The Chore

In order for a user to send a transaction from the browser wallet we need to implement the client send transaction API endpoint 

## Tasks - MVP scope/discovery to inc: 

- [ ] Time box to 1 week to get an basic e2e experience
- [ ] Demo the progress after one week and start to plan what needs to come next
- [ ] Define what has been completed and what still is to be implemented
- [ ] Only encode and sign a transaction with the first wallet using the first key generated, postponing interactions with the UI to a later stage

## Outcome

We want to do the MVP in order to be able to demonstrate this to get feedback on how to improve further
