### ISSUE TITLE
SPIKE: Key aliasing

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/vegawallet-browser#684]
## The Spike

In Palazo there will be a new feature for aliasing a key. For example ENS vs metamask ket name. We already have a concept of a "name" for a key within the wallet.

## Questions we need to answer

- [ ] Aliasing is chain level, the existing naming system is local. How do we differentiate them?
- [ ] Does the wallet support creating a "proper" alias?
- [ ] How do we display alias in the following cases:
    - [ ] No name, no alias (just key string probably)
    - [ ] No name, alias (show alias with some warning/info?)
    - [ ] Name, no alias (show name, with some CTA to create an alias? Or some expliniation this is a local name?)
    - [ ] Name and alias and they match (some green tick, verified thing)
    - [ ] Name and alias and they do not match (some warning to adjust your local name?)
- [ ] How does wallet play with a dApp in this case?
    - [ ] Should the wallet tell console what aliases are present? Issues here around updates.
    - [ ] Should console figure stuff out itself?
    - [ ] Do we pass console both alias and name and allow the dApp to choose?
    - [ ] Do we inform the dApp an alais is "verified" or matches the name?
- [ ] Does the wallet support aliasing natively?

## Tasks

- [ ] Answer the above questions

## Notes

https://github.com/vegaprotocol/specs/pull/2138/files#diff-541801234a3c2b5f0aa18d4c6284e800df9e9e99c7481d78a46ee4e398c99e12R14

**Comment by JonRay15** [comment]
This is all agreed and done on Console side
