### ISSUE TITLE
Support for key 0 creation

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vegawallet-browser#708]
## Chore

In order to fully support metamask snap import we need to be able to support key 0 because this is the default for metamask snap and currently we dont import this into the browser wallet.

## Tasks

- [ ] Update wallet to create the first 3 keys starting from key 0
- [ ] Add some UX to help any users that have previoisly started from 1 and have balances on that 
  - [ ] Detect a wallet that has started from key 1
  - [ ] Probably hide the zero key in these cases and add like a "click to show" type button
  - [ ] Remember last used key (in console)

## Notes

Need a Core ticket to update the CLI to follow this pattern too, we can wait until Colosseo for that
