### ISSUE TITLE
Create automatic releases

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-browser#71]
## The Chore

Set up CI to build extensions for Chrome and Firefox, package them up and publish to github releases

## Tasks

- [x] Find and reuse the code from the existing wallet repo and adjust to work with the browser wallet
- [x] Set up CI to build for Chrome extension, package up and publish to the github releases
- [x] Set up CI to build Firefox extension, package up and publish to the github releases
