### ISSUE TITLE
Start browser wallet app

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-browser#72]
## Story

As a user
I want to install and run the browser wallet extension
So that I can use it with my Vega dapps

## Acceptance Criteria

- [x] I can follow the documented steps to run and install the browser extension
- [x] I can see the browser extension is installed and running

## Tasks

- [x] Document how to install the extension in the browser 

## Background information

Later down the line we would like the extension to be published in the appropriate web stores and there is a ticket to cover this that we will work on later
