### ISSUE TITLE
Share Testflight version and run an incentive around mobile wallet 

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vegawallet-browser#727]
## Chore

What we need to achieve and who for

## Tasks

- [ ] Publish latest version to AppCenter
- [ ] Share it with community
- [ ] Have Dan set up an incentive

**Comment by JonRay15** [comment]
We did this
