### ISSUE TITLE
√ Create new wallet (and key pair) - single

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-browser#73]
## Story

As a user
I want to create a wallet in my vega wallet browser extension
So that I can store my keys  

## Acceptance Criteria

- [ ] I can click a button (or equivalent) to create a wallet
- [ ] I can give my new wallet a name
- [ ] I am given/shown a recovery phrase for the wallet that I can copy/save 
- [ ] I can view my new wallet
- [ ] I can see a new key pair in the wallet I created

## Tasks

- [ ] Create a minimal UI for the steps 
- [ ] Create and save the wallet
- [ ] Create and save keys

## Additional details / background info

Authentication will come later so this A/C will be covered in a separate ticket:
- [ ] I can specify a password for my new wallet

**Comment by pennyandrews** [comment]
Dupe of https://github.com/vegaprotocol/vegawallet-browser/issues/120
