### ISSUE TITLE
Remaining Wallet / Console "jank" requiring refresh

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vegawallet-browser#735]
## Chore

When I tried to connect to Stagnet I got this view but the popup didnt come up and there was no notification in my extension bar.

<img width="340" alt="image" src="https://github.com/vegaprotocol/vegawallet-browser/assets/89918817/09fc616e-4e0f-4b7f-b219-ecd0986af663">

I had to refresh my page and then Console recognised and triggered the popup immediately.

<img width="331" alt="image" src="https://github.com/vegaprotocol/vegawallet-browser/assets/89918817/7d030695-a346-456c-bc5d-9b78fea8734a">

Then I was able to connect and I have been able to interact with the network fine.
I have seen this behaviour a few places… quite often depending on which order you load pages / connect to wallets etc you will end up needing to refresh one or both things to get to the point it connects nicely.  Often what happens is you end up trying to connect, it wont work, then you put your password in, then you refresh and once it refreshes you are already connected. 

## Tasks

- [ ] Work out what exactly is happening
  - [ ] Could be related to having another network connected and then moving to a different one
  - [ ] Jon to work through the scenarios and see which ones require the refresh 
- [ ] 
- [ ]

**Comment by JonRay15** [comment]
I think I've narrowed this down to being an issue when I'm switching my Beta and Mainnet wallet on and off.

So ... do we want to have handling for that?  Or do we not care cos in theory it will go away once we have multinetwork and most ppl are just sitting on one or the other and using it for all networks...

**Comment by JonRay15** [comment]
Now that I'm constantly running Beta and not swapping around I havent encountered this, so I think this is probably ok.

**Comment by JonRay15** [comment]
Closing this as it really does seem to be a result of swapping back and forth between beta and mainnet walets ... now I'm not doing that it is always fine .
