### ISSUE TITLE
Send transactions

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-browser#74]
## Story

As a user
I want the browser wallet to sign and send transactions 
So that I can perform transactions on the Vega platform

## Acceptance Criteria

- [x] a dapp can ask to send a transaction
- [x] the browser wallet can encode the transaction
- [x] the browser wallet can sign a transaction
- [x] a data node can check a transaction
- [x] the browser wallet sends the transaction back to the dapp

## Tasks

- [x] Put the transaction functionality into the sample browser wallet
- [x] Remove hard coded elements
- [x] Validate the data that is given to the browser wallet from the dapp
- [x] Implement client.send_transaction JS API endpoint
- [x] Implement basic error handling

## Additional details / background info

When sending the transaction back to the dapp, for this story the wallet will select a data node at random to send the transaction to. The work to be smart about which data node to send the transaction to will be covered in a later ticket.

For this story, the wallet will select the 'first' network config, wallet and key available. Managing these things will be covered in later tickets.
