### ISSUE TITLE
Issues importing a wallet to iOS

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vegawallet-browser#745]
## Chore

I tried to import my wallet to iOS and got a hanging spinner for a long time. 

Its unclear whether my string was wrong or whether it was just taking a long time or if it was hanging.

Daro also reported similar so maybe it wasnt just me.

## Tasks

- [ ] Investigate the hanging
- [ ] If we do just expect this process to take a long time maybe include a warning for this
- [ ] Can we detect if the string is just wrong and throw an error?
