### ISSUE TITLE
Keep the wallet logged in at all times

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/vegawallet-browser#760]
## The Spike

Background scripts are frequently killed, and we have no way of controlling this. This is in order to preserve battery life, so for the extension we are currently building we have observed that often users are logged out rather quickly.

This spike is to investigate what we can do to mitigate or eliminate the issue.

## Questions we need to answer

- [x] How do we ensure the users wallet is unlocked for a reasonable period of time?
- [x] Can we ensure we can get a connection back each time?
- [x] If this doesnt work do we look at other options?

## Tasks

- [x] Decide on an approach for how we will keep the wallet decrypted for when a user returns after the background script has been killed
- [x] Ensure we are comfortable with the security impact of the approach we are taking

## Acceptance criteria 

- [ ] Do the hacky thing that allows us to keep the wallet logged in at all times
- [ ] Rename to "Vega wallet extension"

## Notes

Other issues to resolve:

- https://github.com/vegaprotocol/vegawallet-browser/issues/798
- https://github.com/vegaprotocol/vegawallet-browser/issues/795

**Comment by JonRay15** [comment]
Needs at least _some_ @emilbayes input on this
