### ISSUE TITLE
Second pass on Metamask Snap 

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vegawallet-browser#766]
## Chore

What we need to achieve and who for

## Tasks

- [ ] Metamask can handle SVG now ... does that help us?
- [ ] Metamask can handle URLs now ... does that help us?
- [ ] Can we optimise the flow of new user >> snap >> vega wallet?
  - [ ] Is there a way to prompt / steer exporting their private key from MM and uploading to Vega Wallet?
  - [ ] Should we alternatively be somehoe prompting them to create a new Vega Wallet and send funds there (to avoid uploading their main MM seed phrase to a new network)?
- [ ] Should we make use of their homepage function?  If we could route them to here we could:
  - [ ] Show people all their MM keys
  - [ ] Promote moving to the Vega Wallet 
  - [ ] Provide some docs around that
- [ ] Can we include something in the TX receipt to prompt people? Either to go to the hompage or to the Vega Wallet?
- [ ] Anything else we can try to improve?

**Comment by JonRay15** [comment]
Superseded by embedded wallet ...
