### ISSUE TITLE
NOTE BACKEND WORK DONE IN MIRO Import network

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-browser#77]
## Story

As a user
I want to be able to import a network configuration to my wallet
So that I can use my wallet with different vega networks

## Acceptance Criteria

- [ ] I can click a button (or equivilent) to import a new network
- [ ] I can input a URL for a network configuration 
- [ ] I can save / submit the network config
- [ ] I am provided with feedback on whether the network was successfully imported (or not) 
- [ ] TEMPORARY A/C my new network automatically overrides a previous one and is selected / connected

## Tasks

- [ ] Create minimal UI for the steps
- [x] Fetch and decode the config
- [x] Validate config
- [x] Save network config

## Additional details / background info

A/C for later stories around viewing the network I've added and selecting it to connect to
