### ISSUE TITLE
Text & row padding in the transaction list

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vegawallet-browser#808]
## Chore

It is not happy 

![image](https://github.com/vegaprotocol/vegawallet-browser/assets/89918817/92450d97-64b0-4bea-8a02-1f2a65135e07)

## Tasks

- [ ] Copy Metamask date grouping approach
- [ ] Make it look nice 
- [ ] Drop the font size

## Notes

![image](https://github.com/vegaprotocol/vegawallet-browser/assets/89918817/de2595df-8532-41f6-bf47-4dc61fb6b27f)
