### ISSUE TITLE
Smart node selection

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-browser#81]
## The Chore

We are currently selecting a node at random to connect to. On testnet we often have a lot of unhealthy nodes so we need to do something cleverer to find a healthy node to connect to.

## Tasks

- [ ] Understand how this is done in the desktop wallet
- [ ] Replicate this logic for browser wallet
- [ ] Ensure we deal with edge cases i.e. what if there are no healthy nodes

## Additional details / background info

The console team are doing something similar but a bit more advanced that we may be able to leverage https://github.com/vegaprotocol/frontend-monorepo/issues/1899
