### ISSUE TITLE
Notify of transaction request - initial

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-browser#82]
## Story

As a user
I want the browser wallet to notify me that there is a transaction request
So that I know I need to take action

## Acceptance Criteria

- [x] In Chrome the wallet extension is bought to the front when there is a transaction request
- [x] In Firefox there is a notification icon to indicate there is a transaction request 
- [x] Neither of these things happen when I already have the extension open - I am just shown the transaction request

## Tasks

- [x] Track pending transaction requests
- [x] Update the UI when a transaction is coming in
- [x] Handle case where the extension is already open when there is a transaction request

## Additional details / background info

This ticket doesn't represent the ideal experience but we want to get something done for now and then implement an improvement once we have defined the target experience
