### ISSUE TITLE
View and reject transaction request

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-browser#83]
## Story

As a user
I want to be able to view the transaction request
So that I understand the details of the transaction and can make a decision whether to approve or reject

## Acceptance Criteria

- [x] If I view the transaction but close the extension before approving or rejecting, I am notified again that I need to act
- [x] I can open the browser extension to view the transaction details
- [ ] I can see when there is more than one transaction I need to approve/reject and there is a way to view and act on them all
- [x] I can see how I can approve or reject the transaction request
- [x] If I reject the transaction request the request goes away and is no longer visible

## Tasks

- [x] Queue up pending transactions
- [x] Make the API for the UI to fetch pending transaction
- [x] Make a rudimentary UI for viewing the transaction
- [x] Handle the case where another transaction request comes in before the previous one has been approved / rejected
