### ISSUE TITLE
Finalise configurable wallet extension

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vegawallet-browser#839]
## Chore

The wallet extension needs to be completely configurable and deployable by other projects.

## Tasks

- [ ] Remove all Vega branding
- [ ] Include ability to provide a basic style sheet to apply branding
- [ ] Make it available for projects to fork
