### ISSUE TITLE
NOTE BACKEND WORK DONE IN MIRO  Approve transaction request - simple

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-browser#84]
## Story

As a user
I want to be able to approve a transaction request
So that I can action the transaction with the dapp I'm using

## Acceptance Criteria

- [x] I can click a button to indicate that I approve the transaction
- [ ] When I have approved a transaction it gets sent and I am shown some kind of in progress indication (even if just a simple spinner)
- [x] If a transaction I approved fails I see a message about the failure and am provided with the ability to retry (TBC do we want to allow people to retry a failed transaction in the wallet or do I have to go back to the dapp?)

## Tasks

- [x] Discuss with team the retry aspect and decide whether to include this
- [x] Notify the backend that the transaction was approved and send it
- [x] If we do the retry - validate based on error type whether we offer the retry option
- [x] On success, notify the UI of this status
