### ISSUE TITLE
Notify of successful transaction

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-browser#85]
## Story

As a user
I want to see the details of my completed transaction
So that I can check the details, share to prove it if needed and troubleshoot if something doesn't seem right

## Acceptance Criteria

- [ ] If the transaction succeeds I am shown some kind of success message
- [ ] If I have the wallet extension open when a transaction succeeds, I am provided with a link to the transaction details page on Vega Block Explorer 

## Tasks

- [ ] Create the UI with the block explorer link
- [x] Check that the network configs include the link to block explorer for at least the networks we need to support for now (if not find someone to add it)

**Comment by JonRay15** [comment]
Not clear that this is particulaly important at the moment. 

Bumping it out for a sprint or two.

**Comment by JonRay15** [comment]
The only way you can know a TX is successful is by querying for your party on the APIs.

We dont think we can use the BE API because this centralised.

There might be a quicker win to just direct you to the BE link.... but need to talk to Edd about race conditions and errors.

**Comment by JonRay15** [comment]
Going to move this to post-October .... while the main trading app is Console this seems unnecssary when Console provides all the toasts anyway.
