### ISSUE TITLE
View available networks

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-browser#87]
## Story

As a wallet user
I want to see imported networks
So that I can understand what networks are supported

## Acceptance Criteria

- [ ] I can get a list of available networks
- [ ] I can see the list of networks

## Tasks

- [ ] Expose the `admin.list_networks` API from the wallet backend
- [ ] Retrieve the list of networks from the UI
- [ ] Display the list of networks
