### ISSUE TITLE
NOTE BACKEND WORK DONE IN MIRO Select a network

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-browser#88]
## Story

As a wallet user
I want to be able to select between imported networks
So that I can choose what network I want to connect to

## Acceptance Criteria

- [x] I can see a list of all networks
- [x] I can select a network
- [ ] I can now use the selected network
- [ ] I can close the wallet and the same network will be selected when I open the wallet again

## Tasks

- [ ] Implement a mechanism for storing user preferences (ie. selected network)
- [x] Use the selected network when doing any API request (eg sending a transaction)
- [ ] Show the selected network in the UI
- [ ] Determine what should happen if the selected network is removed
