### ISSUE TITLE
NOTE BACKEND WORK DONE IN MIRO View network details

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-browser#90]
## Story

As a wallet user
I want to be able to see detailed network configuration
So that I can compare details from imported networks

## Acceptance Criteria

- [x] I can select a network to see details
- [ ] I can see the imported network configuration

## Tasks

- [x] Implement `admin.describe_network`
- [x] Should we save the original `.toml` file or present the configuration as the saved JSON?
- [ ] Create a minimal UI to show the name and details
