### ISSUE TITLE
NOTE BACKEND WORK DONE IN MIRO  Remove network

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-browser#91]
## Story

As a wallet user
I want be able to remove existing network configurations
So that they are no longer an option when selecting networks

## Acceptance Criteria

- [ ] I can remove a network
- [ ] I can close the wallet and the network I removed will still not be visible in the list when I open the wallet again

## Tasks

- [x] Implement `admin.remove_network`
- [ ] Add a way to remove networks from the UI
- [ ] What should happen if the removed network was also the selected network?
