### ISSUE TITLE
COMBINE  Initiate wallet connection

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-browser#92]
## Story

As a dApp developer
I need to be able to connect to the Vega extension
So that I can interact with the wallet

## Acceptance Criteria

- [ ] I can use `client.connect_wallet` on the Vega API
- [ ] I can list permitted keys with `client.list_keys` after permissions are granted
- [ ] If I have no permissions for a given key `client.send_transaction` should fail
- [ ] If I have no permissions at all all `client.*` endpoints should fail except `client.connect_wallet`
- [ ] I can call `client.get_chain_id` without permissions

## Tasks

- [ ] Implement `client.connect_wallet`
- [ ] Add wallet connections to notification flow
- [ ] Update `client.send_transaction` and `client.list_keys` to account for permissions
