### ISSUE TITLE
Disconnect wallet from dapp

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-browser#96]
## Story

As a dApp developer
I want to be able to disconnect from a wallet
So a user can be assured the dApp no longer can talk to the wallet

## Acceptance Criteria

- [x] I can call `client.disconnect_wallet` after successfully calling `client.connect_wallet`
- [x] I can call `client.disconnect_wallet` with no prior connection and get a null response
- [x] A dapp can disconnect the current active connection (not it's pre-approved status i.e. the dapp can re-instate the connection without further approval) 

## Tasks

- [x] Write unit tests
- [x] Write end to end tests
- [x] Code review
- [x] Team verify acceptance criteria met
- [x] Exploratory QA testing 
- [x] Capture bugs and new edge cases in tickets (this one or new TBD) 
- [x] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [x] Add story and A/Cs to spec doc 
- [ ] Review with stakeholders 
- [ ] Release
