### ISSUE TITLE
√ Select a wallet to connect (no auth)

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-browser#98]
## Story

As a wallet user
I want select which wallet can be accessed by a dApp
So that I have control over which keys are accessible to the dApp

## Acceptance Criteria

- [ ] I can see a list of wallets
- [ ] I can select a single wallet to be accessible
- [ ] I can cancel the selection process (which will ultimately cancel the connection attempt)

## Tasks

- [ ] Simple UI integrated into the process of #92
